Repository bloomwalletio/bloom, pull requests merged in 2023-11, with the labels that each got.

#1371 release: desktop 0.1.0
  .github/workflows/reusable_build.yml
  packages/desktop/components/popup/popups/MintNftConfirmationPopup.svelte
  packages/desktop/electron-builder-config.ts
  packages/desktop/features/app.features.ts
  packages/desktop/features/contacts.features.ts
  packages/desktop/features/onboarding.features.ts
  packages/desktop/features/settings.features.ts
  packages/desktop/package.json
  packages/desktop/views/components/Background.svelte
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/dashboard/send-flow/views/SelectTokenView.svelte
  packages/desktop/views/settings/views/SettingsListForCategory.svelte
  packages/shared/src/components/atoms/LedgerIllustration.svelte
  packages/shared/src/components/modals/Modal.svelte
  packages/shared/src/components/organisms/NodeConfigurationForm.svelte
  packages/shared/src/lib/core/layer-2/actions/generateAndStoreEvmAddressForAccounts.ts
  packages/shared/src/lib/core/layer-2/constants/fallback-estimated-gas.constant.ts
  packages/shared/src/lib/core/market/enums/market-currency.enum.ts
  packages/shared/src/lib/core/network/classes/iscp-chain.class.ts
  packages/shared/src/lib/core/network/utils/canAccountMakeStardustTransaction.ts
  packages/shared/src/lib/core/network/utils/index.ts
  packages/shared/src/lib/core/wallet/actions/send/signAndSendEvmTransaction.ts
  packages/shared/src/lib/core/wallet/actions/signMessage.ts
  packages/shared/src/lib/features/interfaces/app-features.interface.ts
  packages/shared/src/locales/en.json
Labels: type:chore

#1391 chore: enable contact book
  packages/desktop/features/contacts.features.ts
Labels: type:chore

#1394 chore: update UI kit version
  packages/shared/package.json
  yarn.lock
Labels: type:ui

#1414 enhancement: polish contact book forms
  packages/desktop/views/dashboard/drawers/contact-book/views/AddContactDrawer.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/AddNetworkAddressDrawer.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/EditNetworkAddressesDrawer.svelte
  packages/shared/src/components/molecules/NetworkRecipientItem.svelte
  packages/shared/src/locales/en.json
Labels: type:enhancement, type:ui

#1415 feat: add group headers in contact list
  packages/desktop/components/ContactCard.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/ContactListDrawer.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/components/ContactList.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/components/index.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement, context:contacts

#1406 focus window on session request
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionRequest.handler.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/test/mocks/platform.mock.ts
Labels: type:enhancement

#1417 feat: add QR code drawer for contact addresses
  packages/desktop/components/ContactAddressCard.svelte
  packages/desktop/views/dashboard/drawers/contact-book/ContactBookRouterView.svelte
  packages/desktop/views/dashboard/drawers/contact-book/contact-book-route.enum.ts
  packages/desktop/views/dashboard/drawers/contact-book/contact-book-router.ts
  packages/desktop/views/dashboard/drawers/contact-book/views/ContactAddressDrawer.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/index.ts
  packages/shared/src/lib/core/contact/stores/index.ts
  packages/shared/src/lib/core/contact/stores/selected-contact-network-address.store.ts
  packages/shared/src/locales/en.json
Labels: type:feature, context:contacts

#1419 enhancement: color picker to contact book forms
  packages/desktop/views/dashboard/drawers/contact-book/views/AddContactDrawer.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/EditContactDrawer.svelte
  packages/shared/src/lib/core/contact/classes/contact-manager.class.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement, context:contacts

#1434 ui: polish contact book
  packages/desktop/components/ContactAddressCard.svelte
  packages/desktop/components/ContactCard.svelte
  packages/desktop/components/NetworkCard.svelte
  packages/desktop/components/drawers/DrawerTemplate.svelte
  packages/desktop/views/dashboard/drawers/contact-book/views/AddContactDrawer.svelte
  packages/shared/src/lib/core/network/constants/default-explorer-urls.constant.ts
  packages/shared/src/lib/core/network/constants/explorer-endpoints.constant.ts
  packages/shared/src/lib/core/network/enums/explorer-endpoint.enum.ts
  packages/shared/src/locales/en.json
Labels: type:ui

#1421 fix: system theme
  packages/desktop/App.svelte
  packages/desktop/components/ProposalAnswer.svelte
  packages/desktop/components/ProposalCard.svelte
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/views/Splash.svelte
  packages/desktop/views/dashboard/send-flow/views/components/DateTimePickerMenu.svelte
  packages/desktop/views/dashboard/send-flow/views/components/StorageDepositButton.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityActionSection.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityAssetSection.svelte
  packages/desktop/views/settings/views/general/Theme.svelte
  packages/shared/src/components/Animation.svelte
  packages/shared/src/components/Illustration.svelte
  packages/shared/src/components/Logo.svelte
  packages/shared/src/components/QR.svelte
  packages/shared/src/components/Tooltip.svelte
  packages/shared/src/components/atoms/Pane.svelte
  packages/shared/src/components/boxes/AddressBox.svelte
  packages/shared/src/components/tiles/TokenAvailableBalanceTile.svelte
  packages/shared/src/lib/core/app/actions/getAndUpdateDarkMode.ts
  packages/shared/src/lib/core/app/actions/index.ts
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/src/lib/core/app/stores/app-settings.store.ts
  packages/shared/src/lib/core/app/stores/dark-mode.store.ts
  packages/shared/src/lib/core/app/stores/index.ts
  packages/shared/src/lib/core/app/utils/index.ts
  packages/shared/src/lib/core/app/utils/shouldBeDarkMode.ts
  packages/shared/src/locales/en.json
  packages/shared/test/mocks/platform.mock.ts
Labels: context:settings, type:fix, type:ui

#1443 fix: update Box and Input bg color to surface
  packages/shared/src/components/boxes/Box.svelte
  packages/shared/src/components/inputs/Input.svelte
Labels: type:fix

#1448 ui: dark mode on connect ledger view
  packages/desktop/views/onboarding/views/create-from-ledger/views/ConnectLedgerView.svelte
Labels: type:ui

#1420 enhancement: use explorer API to track ERC20 tokens
  packages/shared/src/lib/core/account/actions/tryCreateAdditionalAccount.ts
  packages/shared/src/lib/core/layer-2/actions/checkForUntrackedTokens.ts
  packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts
  packages/shared/src/lib/core/layer-2/actions/index.ts
  packages/shared/src/lib/core/layer-2/actions/pollL2BalanceForAccount.ts
  packages/shared/src/lib/core/layer-2/utils/fetchL2BalanceForAllAccounts.ts
  packages/shared/src/lib/core/network/classes/iscp-chain.class.ts
  packages/shared/src/lib/core/network/constants/index.ts
  packages/shared/src/lib/core/network/enums/explorer-endpoint.enum.ts
  packages/shared/src/lib/core/network/interfaces/chain.interface.ts
  packages/shared/src/lib/core/token/enums/token-standard.enum.ts
  packages/shared/src/lib/core/token/interfaces/erc20-token-with-balance.interface.ts
  packages/shared/src/lib/core/token/interfaces/index.ts
Labels: type:enhancement

#1447 chore: update bloom ui kit to 0.18.37
  packages/shared/package.json
  yarn.lock
Labels: type:chore

#1454 fix: adjust logic for manually untracking tokens
  packages/desktop/components/menus/TokenActionsMenu.svelte
  packages/desktop/components/menus/TokenListMenu.svelte
  packages/desktop/components/popup/popups/ImportErc20TokenFormPopup.svelte
  packages/shared/src/lib/core/activity/actions/calculateAndAddPersistedTokenBalanceChange.ts
  packages/shared/src/lib/core/layer-2/actions/checkForUntrackedTokens.ts
  packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts
  packages/shared/src/lib/core/layer-2/utils/fetchL2BalanceForAllAccounts.ts
  packages/shared/src/lib/core/network/classes/iscp-chain.class.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-3-to-4.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-0-to-1.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-map.ts
  packages/shared/src/lib/core/profile/stores/profiles.store.ts
  packages/shared/src/lib/core/token/actions/removeTrackedTokenFromActiveProfile.ts
  packages/shared/src/lib/core/token/enums/index.ts
  packages/shared/src/lib/core/token/enums/token-tracking-status.enum.ts
  packages/shared/src/lib/core/token/types/tracked-tokens.type.ts
  packages/shared/src/lib/core/wallet/actions/addNewTrackedTokenToActiveProfile.ts
  packages/shared/src/lib/core/wallet/actions/hasTokenBeenUntracked.ts
  packages/shared/src/lib/core/wallet/actions/index.ts
  packages/shared/src/lib/core/wallet/actions/isTrackedTokenAddress.ts
  packages/shared/src/locales/en.json
Labels: context:layer-2, context:wallet, type:fix

#1478 chore: remove unused getCurrencySymbol
  packages/desktop/views/dashboard/wallet/tab-section/portfolio/PortfolioTab.svelte
  packages/shared/src/lib/core/i18n/utils/getCurrencySymbol.ts
  packages/shared/src/lib/core/i18n/utils/index.ts
Labels: type:chore

#1461 release: version `desktop-0.1.1`
  packages/desktop/components/drawers/Drawer.svelte
  packages/desktop/package.json
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
  packages/shared/src/locales/en.json
Labels: type:chore

#1471 feat: add logo from CoinGecko ShimmerEVM registered tokens
  packages/desktop/App.svelte
  packages/shared/src/components/avatars/TokenAvatar.svelte
  packages/shared/src/lib/core/market/actions/getAndUpdateMarketPrices.ts
  packages/shared/src/lib/core/market/actions/getAndUpdateShimmerEvmTokensMetadata.ts
  packages/shared/src/lib/core/market/actions/getMarketPrices.ts
  packages/shared/src/lib/core/market/actions/index.ts
  packages/shared/src/lib/core/market/apis/coingecko.api.ts
  packages/shared/src/lib/core/market/apis/index.ts
  packages/shared/src/lib/core/market/enums/coingecko-api-endpoint.enum.ts
  packages/shared/src/lib/core/market/enums/coingecko-network-id.enum.ts
  packages/shared/src/lib/core/market/enums/index.ts
  packages/shared/src/lib/core/market/interfaces/coingecko-coin-image.interface.ts
  packages/shared/src/lib/core/market/interfaces/coingecko-coin.interface.ts
  packages/shared/src/lib/core/market/interfaces/index.ts
  packages/shared/src/lib/core/market/stores/coingecko-tokens-metadata.ts
  packages/shared/src/lib/core/market/stores/index.ts
  packages/shared/src/lib/core/market/utils/getImageUrlFromToken.ts
  packages/shared/src/lib/core/market/utils/index.ts
Labels: type:feature

#1505 fix: type error
  packages/shared/src/lib/core/ledger/utils/isLedgerDeviceMatchingActiveProfile.ts
  packages/shared/src/lib/core/network/actions/getAndUpdateNodeInfo.ts
  packages/shared/src/lib/core/profile-manager/actions/destroyProfileManager.ts
  packages/shared/src/lib/core/profile-manager/api/getNodeInfo.ts
  packages/shared/src/lib/core/profile-manager/stores/profile-manager.store.ts
Labels: type:chore, type:enhancement

#1503 feat: add support for ERC20 token prices from CoinGecko
  packages/shared/src/lib/core/market/actions/getAndUpdateMarketPrices.ts
  packages/shared/src/lib/core/market/apis/coingecko.api.ts
  packages/shared/src/lib/core/market/stores/coingecko-tokens-metadata.store.ts
  packages/shared/src/lib/core/market/stores/index.ts
  packages/shared/src/lib/core/market/stores/shimmer-evm-address-to-coingecko-id-map.ts
  packages/shared/src/lib/core/market/types/market-coin-prices.type.ts
  packages/shared/src/lib/core/token/actions/getAccountTokensForSelectedAccount.ts
Labels: type:feature

#1512 enhancement: use irc30 logo url in token avatar
  packages/shared/src/lib/core/market/utils/getImageUrlFromToken.ts
Labels: type:enhancement
