Repository bloomwalletio/bloom, pull requests merged in 2023-12, with the labels that each got.

#1544 update @bloomwalletio/ui
  packages/shared/package.json
  packages/shared/tailwind.config.js
  yarn.lock
Labels: scope:dependencies

#1562 fix: windows focus
  packages/desktop/lib/electron/processes/main.process.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/eth_transaction.handler.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionRequest.handler.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/sign_message.handler.ts
Labels: os:windows, type:enhancement, type:fix

#1543 refactor: basic redesign of SliderInput
  packages/desktop/components/popup/popups/BurnNativeTokensPopup.svelte
  packages/shared/src/components/inputs/Dropdown.svelte
  packages/shared/src/components/inputs/Dropdown2.svelte
  packages/shared/src/components/inputs/InputContainer.svelte
  packages/shared/src/components/inputs/SliderInput.svelte
  packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte
  packages/shared/src/components/inputs/UnitInput.svelte
  packages/shared/src/components/inputs/index.ts
  packages/shared/src/components/labels/TokenLabel.svelte
Labels: type:refactor, type:ui

#1501 feat: add automatic tracking for ERC721 NFTs
  packages/desktop/components/popup/popups/MintNftFormPopup.svelte
  packages/desktop/views/dashboard/send-flow/views/SelectRecipientView.svelte
  packages/shared/src/components/molecules/activity-info/NftMetadataInformation.svelte
  packages/shared/src/lib/core/layer-2/abis/erc165.abi.ts
  packages/shared/src/lib/core/layer-2/abis/erc721.abi.ts
  packages/shared/src/lib/core/layer-2/abis/index.ts
  packages/shared/src/lib/core/layer-2/actions/pollL2BalanceForAccount.ts
  packages/shared/src/lib/core/layer-2/constants/evm-contract-abis.constant.ts
  packages/shared/src/lib/core/layer-2/constants/index.ts
  packages/shared/src/lib/core/layer-2/enums/contract-type.enum.ts
  packages/shared/src/lib/core/layer-2/enums/erc721-interface-id.enum.ts
  packages/shared/src/lib/core/layer-2/enums/index.ts
  packages/shared/src/lib/core/layer-2/utils/fetchL2BalanceForAllAccounts.ts
  packages/shared/src/lib/core/layer-2/utils/getAbiForContractType.ts
  packages/shared/src/lib/core/layer-2/utils/index.ts
  packages/shared/src/lib/core/network/classes/evm-explorer-api.class.ts
  packages/shared/src/lib/core/network/classes/iscp-chain.class.ts
  packages/shared/src/lib/core/network/interfaces/explorer-api.interface.ts
  packages/shared/src/lib/core/network/interfaces/explorer-asset-metadata.interface.ts
  packages/shared/src/lib/core/nfts/actions/addNewTrackedNftToActiveProfile.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/nfts/actions/index.ts
  packages/shared/src/lib/core/nfts/actions/isNftPersisted.ts
  packages/shared/src/lib/core/nfts/constants/default-nft-token-id.constant.ts
  packages/shared/src/lib/core/nfts/constants/index.ts
  packages/shared/src/lib/core/nfts/enums/index.ts
  packages/shared/src/lib/core/nfts/enums/nft-standard.enum.ts
  packages/shared/src/lib/core/nfts/interfaces/erc721-contract-metadata.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/erc721-token-metadata.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/index.ts
  packages/shared/src/lib/core/nfts/interfaces/irc27-metadata.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/persisted-nft-data.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/persisted-nft-store.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/persisted-nft.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/persisted-nfts.interface.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/persisted-nft-data.store.ts
  packages/shared/src/lib/core/nfts/stores/persisted-nfts.store.ts
  packages/shared/src/lib/core/nfts/types/index.ts
  packages/shared/src/lib/core/nfts/types/persisted-nft.type.ts
  packages/shared/src/lib/core/nfts/utils/checkIfNftShouldBeDownloaded.ts
  packages/shared/src/lib/core/nfts/utils/getPersistedErc721NftFromContract.ts
  packages/shared/src/lib/core/nfts/utils/index.ts
  packages/shared/src/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/src/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/src/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/src/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/src/lib/core/token/enums/token-standard.enum.ts
  packages/shared/src/lib/core/utils/api.ts
Labels: context:collectibles, context:layer-2, type:feature

#1519 feat: basic iota network support
  packages/desktop/features/onboarding.features.ts
  packages/desktop/views/components/ButtonTile.svelte
  packages/desktop/views/dashboard/wallet/tab-section/portfolio/components/TokenListRow.svelte
  packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/shared/src/components/avatars/NetworkAvatar.svelte
  packages/shared/src/components/avatars/TokenAvatar.svelte
  packages/shared/src/lib/auxiliary/icon/constants/default-network-icon.ts
  packages/shared/src/lib/auxiliary/icon/constants/default-token-icon.ts
  packages/shared/src/lib/contexts/onboarding/enums/onboarding-network-type.enum.ts
  packages/shared/src/lib/core/market/actions/getAndUpdateMarketPrices.ts
  packages/shared/src/lib/core/market/enums/market-coin-id.enum.ts
  packages/shared/src/lib/core/network/constants/default-base-token.constant.ts
  packages/shared/src/lib/core/network/constants/default-bech32-hrp.constant.ts
  packages/shared/src/lib/core/network/constants/default-chain-configurations.constant.ts
  packages/shared/src/lib/core/network/constants/default-coin-type.constant.ts
  packages/shared/src/lib/core/network/constants/default-explorer-urls.constant.ts
  packages/shared/src/lib/core/network/constants/default-network-metadata.constant.ts
  packages/shared/src/lib/core/network/constants/default-node-urls.constant.ts
  packages/shared/src/lib/core/network/constants/default-protocol.constant.ts
  packages/shared/src/lib/core/network/constants/explorer-endpoints.constant.ts
  packages/shared/src/lib/core/network/constants/faucet-urls.constant.ts
  packages/shared/src/lib/core/network/constants/index.ts
  packages/shared/src/lib/core/network/enums/stardust-network-name.enum.ts
  packages/shared/src/lib/core/network/enums/supported-network-id.enum.ts
  packages/shared/src/lib/core/network/tests/network.test.ts
  packages/shared/src/lib/core/network/utils/getNetworkIdFromOnboardingNetworkType.ts
  packages/shared/src/lib/core/network/utils/getOnboardingNetworkTypeFromNetworkId.ts
  packages/shared/src/lib/core/token/actions/getAccountTokensForSelectedAccount.ts
Labels: type:feature

#1567 refactor: improve error handling for ERC721 NFT tracking
  packages/shared/src/lib/core/layer-2/actions/pollL2BalanceForAccount.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/nfts/actions/isNftPersisted.ts
  packages/shared/src/lib/core/nfts/utils/getPersistedErc721NftFromContract.ts
Labels: context:collectibles, context:layer-2, type:refactor

#1580 chore: update iota sdk to 1.1.4
  packages/shared/package.json
  yarn.lock
Labels: type:chore

#1579 fix: uncaught error on reject
  packages/shared/src/lib/auxiliary/wallet-connect/utils/approveSession.ts
  packages/shared/src/lib/auxiliary/wallet-connect/utils/rejectSession.ts
Labels: type:fix

#1584 fix: untrack erc-20 interface of the base token
  packages/shared/src/lib/core/layer-2/actions/checkForUntrackedTokens.ts
  packages/shared/src/lib/core/layer-2/constants/base-token-contract-address.constant.ts
  packages/shared/src/lib/core/layer-2/constants/index.ts
  packages/shared/src/lib/core/token/actions/getAccountTokensForAccount.ts
Labels: type:enhancement, type:fix

#1588 feat: support details view for ERC721 NFTs
  packages/desktop/components/menus/CollectibleDetailsMenu.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectibleDetails.svelte
  packages/desktop/views/dashboard/collectibles/components/Erc721CollectibleDetails.svelte
  packages/desktop/views/dashboard/collectibles/components/Irc27CollectibleDetails.svelte
  packages/desktop/views/dashboard/collectibles/components/index.ts
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/shared/src/lib/core/network/classes/evm-explorer-api.class.ts
  packages/shared/src/lib/core/network/constants/default-explorer-urls.constant.ts
  packages/shared/src/lib/core/network/constants/explorer-endpoints.constant.ts
  packages/shared/src/lib/core/network/enums/explorer-endpoint.enum.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/nfts/enums/nft-standard.enum.ts
  packages/shared/src/lib/core/nfts/interfaces/erc721-token-metadata.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/index.ts
  packages/shared/src/lib/core/nfts/interfaces/irc27-metadata.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/nft-attribute.interface.ts
  packages/shared/src/lib/core/nfts/utils/buildNftFromPersistedErc721Nft.ts
  packages/shared/src/lib/core/nfts/utils/buildPersistedErc721Nft.ts
  packages/shared/src/lib/core/nfts/utils/composeUrlFromNftUri.ts
  packages/shared/src/lib/core/nfts/utils/index.ts
  packages/shared/src/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/src/lib/core/token/enums/token-standard.enum.ts
  packages/shared/src/locales/en.json
Labels: context:collectibles, context:layer-2, type:feature

#1593 fix: errors in locale
  packages/shared/src/locales/af.json
  packages/shared/src/locales/ar.json
  packages/shared/src/locales/bg.json
  packages/shared/src/locales/ca.json
  packages/shared/src/locales/cs.json
  packages/shared/src/locales/da.json
  packages/shared/src/locales/de.json
  packages/shared/src/locales/el.json
  packages/shared/src/locales/en.json
  packages/shared/src/locales/eo.json
  packages/shared/src/locales/es-ES.json
  packages/shared/src/locales/es-LA.json
  packages/shared/src/locales/et.json
  packages/shared/src/locales/fa.json
  packages/shared/src/locales/fi.json
  packages/shared/src/locales/fr.json
  packages/shared/src/locales/he.json
  packages/shared/src/locales/hi.json
  packages/shared/src/locales/hr.json
  packages/shared/src/locales/hu.json
  packages/shared/src/locales/id.json
  packages/shared/src/locales/it.json
  packages/shared/src/locales/ja.json
  packages/shared/src/locales/ko.json
  packages/shared/src/locales/ku.json
  packages/shared/src/locales/lv.json
  packages/shared/src/locales/mk.json
  packages/shared/src/locales/nl.json
  packages/shared/src/locales/no.json
  packages/shared/src/locales/pl.json
  packages/shared/src/locales/pt-BR.json
  packages/shared/src/locales/pt-PT.json
  packages/shared/src/locales/ro.json
  packages/shared/src/locales/ru.json
  packages/shared/src/locales/si.json
  packages/shared/src/locales/sk.json
  packages/shared/src/locales/sl.json
  packages/shared/src/locales/sq.json
  packages/shared/src/locales/sr.json
  packages/shared/src/locales/sv.json
  packages/shared/src/locales/uk.json
  packages/shared/src/locales/ur.json
  packages/shared/src/locales/vi.json
  packages/shared/src/locales/zh-CN.json
  packages/shared/src/locales/zh-TW.json
Labels: type:fix

#1602 fix: nft description height
  packages/desktop/views/dashboard/collectibles/components/CollectibleDetails.svelte
Labels: type:fix

#1609 fix: creates one account if no accounts are recovered in balance finder
  packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte
Labels: type:fix

#1605 Feat: enable additional languages
  packages/desktop/features/app.features.ts
  packages/desktop/views/settings/views/SettingsSidebar.svelte
  packages/shared/src/components/inputs/AmountInput.svelte
  packages/shared/src/lib/features/interfaces/app-features.interface.ts
Labels: type:enhancement

#1619 fix: wallet connect errors
  packages/shared/package.json
  packages/shared/src/lib/auxiliary/deep-link/handlers/dapps/operations/handleDeepLinkAddWCConnectionOperation.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/disconnectDapp.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/initializeWalletConnect.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/removeDapp.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionRequest.handler.ts
  yarn.lock
Labels: type:fix

#1610 feat: multi address algorithm in balance finder for IOTA profiles
  packages/desktop/components/popup/popups/SyncAccountsPopup.svelte
  packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte
  packages/shared/src/lib/core/profile/constants/default-account-recovery-configuration.constant.ts
Labels: type:feature

#1626 feat: multi address activities
  packages/shared/src/lib/core/account/actions/buildAccountState.ts
  packages/shared/src/lib/core/account/actions/buildAccountStateAndPersistedData.ts
  packages/shared/src/lib/core/account/interfaces/account-state.interface.ts
  packages/shared/src/lib/core/account/interfaces/persisted-account-data.interface.ts
  packages/shared/src/lib/core/activity/utils/getDirectionFromTransaction.ts
  packages/shared/src/lib/core/activity/utils/getSenderFromTransaction.ts
  packages/shared/src/lib/core/activity/utils/outputs/preprocessGroupedOutputs.ts
  packages/shared/src/lib/core/activity/utils/outputs/preprocessTransaction.ts
  packages/shared/src/lib/core/profile/actions/active-accounts/findActiveAccountWithAddress.ts
Labels: type:feature

#1630 fix: IOTA balances recovery for Ledger
  packages/desktop/components/popup/popups/SyncAccountsPopup.svelte
  packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte
  packages/desktop/views/onboarding/views/restore-profile/views/ClaimFinderView.svelte
  packages/shared/src/lib/core/ledger/utils/index.ts
  packages/shared/src/lib/core/ledger/utils/ledgerRaceConditionProtectionWrapper.ts
  packages/shared/src/lib/core/profile/constants/default-account-recovery-configuration.constant.ts
Labels: context:onboarding, type:fix, scope:ledger

#1631 enhancement: iota genesis activities
  packages/desktop/components/popup/popups/ActivityDetailsPopup.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityActionSection.svelte
  packages/shared/src/lib/core/activity/enums/activity-direction.enum.ts
  packages/shared/src/lib/core/activity/utils/generateActivities.ts
  packages/shared/src/lib/core/activity/utils/getActivityTileTitle.ts
  packages/shared/src/lib/core/activity/utils/getDirectionFromTransaction.ts
  packages/shared/src/lib/core/activity/utils/getSenderFromTransaction.ts
  packages/shared/src/lib/core/activity/utils/helper/getSendingInformation.ts
  packages/shared/src/lib/core/activity/utils/outputs/preprocessGroupedOutputs.ts
  packages/shared/src/lib/core/network/constants/explorer-endpoints.constant.ts
  packages/shared/src/lib/core/network/enums/explorer-endpoint.enum.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement
