Repository bloomwalletio/bloom, pull requests merged in 2024-07, with the labels that each got.

#2680 release: desktop version `1.1.1`
  .github/workflows/ci.lint.yml
  .github/workflows/ci.snyk.yml
  .github/workflows/ci.test.yml
  .github/workflows/ci.ts.yml
  .github/workflows/crowdin.yml
  .github/workflows/reusable_build.yml
  .github/workflows/reusable_release.yml
  packages/desktop/lib/electron/utils/analytics.utils.ts
  packages/desktop/package.json
  packages/shared/package.json
  packages/shared/src/lib/core/activity/utils/evm/generateBaseEvmActivity.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-15-to-16.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-8-to-9.ts
Labels: type:chore

#2702 refactor: MarketCurrency to FiatCurrency & CryptoCurrency
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/desktop/views/settings/views/profile/Currency.svelte
  packages/shared/src/lib/auxiliary/third-party/utils/buildPersistedProfileFromThirdPartyPersistedProfile.ts
  packages/shared/src/lib/core/app/interfaces/transak-window-data.interface.ts
  packages/shared/src/lib/core/i18n/utils/formatCurrency.ts
  packages/shared/src/lib/core/i18n/utils/getDecimalSeparator.ts
  packages/shared/src/lib/core/i18n/utils/getGroupSeparator.ts
  packages/shared/src/lib/core/market/actions/getAndUpdateMarketPrices.ts
  packages/shared/src/lib/core/market/apis/coingecko.api.ts
  packages/shared/src/lib/core/market/constants/default-market-currency.constant.ts
  packages/shared/src/lib/core/market/enums/crypto-currency.enum.ts
  packages/shared/src/lib/core/market/enums/fiat-currency.enum.ts
  packages/shared/src/lib/core/market/enums/index.ts
  packages/shared/src/lib/core/market/enums/market-currency.enum.ts
  packages/shared/src/lib/core/market/types/index.ts
  packages/shared/src/lib/core/market/types/market-currency.type.ts
  packages/shared/src/lib/core/market/types/market-prices.type.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-22-to-23.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-12-to-13.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-map.ts
Labels: type:refactor

#2709 feat: Transak API get crypto and fiat currencies
  packages/shared/src/lib/auxiliary/transak/apis/index.ts
  packages/shared/src/lib/auxiliary/transak/apis/transak.api.ts
  packages/shared/src/lib/auxiliary/transak/constants/index.ts
  packages/shared/src/lib/auxiliary/transak/constants/transak-api-base-url.constant.ts
  packages/shared/src/lib/auxiliary/transak/constants/transak-api-production-base-url.constant.ts
  packages/shared/src/lib/auxiliary/transak/constants/transak-api-staging-base-url.constant.ts
  packages/shared/src/lib/auxiliary/transak/enums/index.ts
  packages/shared/src/lib/auxiliary/transak/enums/transak-api-endpoint.enum.ts
  packages/shared/src/lib/auxiliary/transak/interfaces/index.ts
  packages/shared/src/lib/auxiliary/transak/interfaces/transak-api-crypto-currencies-response.interface.ts
  packages/shared/src/lib/auxiliary/transak/interfaces/transak-api-fiat-currencies-response.interface.ts
Labels: type:feature

#2716 feat: adds accounts and profiles count in analytics
  packages/desktop/App.svelte
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/lib/electron/utils/analytics.utils.ts
  packages/shared/src/lib/core/app/interfaces/analytics-initialisation-data.interface.ts
  packages/shared/src/lib/core/app/interfaces/index.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
Labels: type:feature, type:fix, type:refactor

#2726 fix: `en` locale string typo
  packages/shared/src/locales/en.json
Labels: type:fix

#2737 refactor: cleanup add remove network
  packages/desktop/views/dashboard/drawers/network-config/views/components/AddEvmChainForm.svelte
  packages/desktop/views/dashboard/drawers/network-config/views/components/NetworkActionsMenu.svelte
  packages/shared/src/lib/core/network/actions/addNewEvmNetwork.ts
  packages/shared/src/lib/core/network/actions/index.ts
  packages/shared/src/lib/core/network/actions/removeExistingEvmNetwork.ts
  packages/shared/src/lib/core/network/classes/stardust-network.class.ts
  packages/shared/src/lib/core/network/interfaces/stardust-network.interface.ts
  packages/shared/src/lib/core/network/stores/networks.store.ts
Labels: type:refactor

#2743 feat: Transak window as a Popup
  packages/desktop/components/ConfirmationDialog.svelte
  packages/desktop/components/popup/Popup.svelte
  packages/desktop/components/popup/popups/TransakFramePopup.svelte
  packages/desktop/lib/auxiliary/popup/enums/popup-id.enum.ts
  packages/desktop/lib/auxiliary/popup/interfaces/popup-state.interface.ts
  packages/desktop/lib/electron/preloads/transak.preload.ts
  packages/desktop/views/dashboard/buy-sell/components/TransakConnectionBanner.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakCryptoCurrencyAmountTile.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakExchangePanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakInfoPanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/index.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/assets/logos/transak-full.svg
  packages/shared/assets/logos/transak-icon.svg
  packages/shared/assets/logos/transak-text.svg
  packages/shared/assets/logos/transak.svg
  packages/shared/src/lib/auxiliary/transak/actions/updateTransakCryptoCurrencies.ts
  packages/shared/src/lib/auxiliary/transak/stores/transak-crypto-currencies.store.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2754 enhancement: validate network config on add chain form
  packages/desktop/views/dashboard/drawers/network-config/views/components/AddEvmChainForm.svelte
  packages/shared/src/lib/auxiliary/blockscout/api/blockscout.api.ts
  packages/shared/src/lib/core/layer-2/actions/checkForUntrackedTokens.ts
  packages/shared/src/lib/core/network/classes/evm-network.class.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/transactions/actions/fetchAndPersistTransactionsForAccounts.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#2753 feat: buy/sell quotations timer
  packages/desktop/components/popup/popups/TransakFramePopup.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakConnectionBanner.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakCryptoCurrencyAmountTile.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakExchangePanel.svelte
  packages/shared/src/locales/en.json
Labels: type:feature

#2763 feat: adds isEthereumBlindSigningRequiredByVersion condition
  packages/shared/package.json
  packages/shared/src/lib/core/ledger/classes/ledger.class.ts
  yarn.lock
Labels: type:feature, type:fix
