Repository bloomwalletio/bloom, pull requests merged in 2024-09, with the labels that each got.

#2816 fix: remove tanglebay shimmer node
  packages/shared/src/lib/core/network/constants/default-node-urls.constant.ts
  packages/shared/src/lib/core/network/tests/network.test.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-23-to-24.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-13-to-14.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-map.ts
Labels: type:fix

#2817 feat: add known chains to add chain form
  packages/desktop/features/network.features.ts
  packages/desktop/views/dashboard/drawers/network-config/NetworkConfigRouterView.svelte
  packages/desktop/views/dashboard/drawers/network-config/network-config-route.enum.ts
  packages/desktop/views/dashboard/drawers/network-config/views/AddCustomNetworkDrawer.svelte
  packages/desktop/views/dashboard/drawers/network-config/views/ConnectedNetworksDrawer.svelte
  packages/desktop/views/dashboard/drawers/network-config/views/ManageNetworksDrawer.svelte
  packages/desktop/views/dashboard/drawers/network-config/views/components/NetworkActionsMenu.svelte
  packages/desktop/views/dashboard/drawers/network-config/views/index.ts
  packages/shared/package.json
  packages/shared/src/components/avatars/NetworkAvatar.svelte
  packages/shared/src/lib/auxiliary/icon/constants/default-network-icon.ts
  packages/shared/src/lib/core/network/constants/default-evm-network-configurations-for-stardust-network.constant.ts
  packages/shared/src/lib/core/network/constants/default-explorer-urls.constant.ts
  packages/shared/src/lib/core/network/constants/supported-network-id.constant.ts
  packages/shared/src/lib/core/network/enums/chain-id.enum.ts
  packages/shared/src/lib/features/interfaces/network-features.interface.ts
  packages/shared/src/locales/en.json
  yarn.lock
Labels: type:feature

#2797 refactor+fix: ledger app name check
  packages/desktop/components/popup/popups/SyncAccountsPopup.svelte
  packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte
  packages/desktop/views/onboarding/views/create-from-ledger/views/ConnectLedgerView.svelte
  packages/desktop/views/onboarding/views/create-from-ledger/views/InstallLedgerView.svelte
  packages/desktop/views/onboarding/views/create-from-ledger/views/ledger-connection-guide/components/LedgerAppOpen.svelte
  packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte
  packages/shared/src/lib/auxiliary/third-party/constants/network-name-to-stardust-network-id-map.constant.ts
  packages/shared/src/lib/core/ledger/actions/checkOrConnectLedger.ts
  packages/shared/src/lib/core/ledger/utils/handleLedgerError.ts
  packages/shared/src/lib/core/ledger/utils/isLedgerDeviceMatchingActiveProfile.ts
  packages/shared/src/lib/core/network/utils/getNetworkIdFromOnboardingNetworkType.ts
  packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleTransactionProgressEvent.ts
  packages/shared/src/lib/core/profile/actions/active-profile/checkActiveProfileAuth.ts
  packages/shared/src/lib/core/profile/actions/active-profile/getProfileLedgerAppName.ts
  packages/shared/src/lib/core/profile/actions/active-profile/index.ts
Labels: type:fix

#2825 feat: adds initial BNB chain support
  packages/shared/src/lib/auxiliary/explorer/enums/etherscan-explorer-endpoint.enum.ts
  packages/shared/src/lib/auxiliary/explorer/enums/explorer-type.enum.ts
  packages/shared/src/lib/auxiliary/explorer/enums/index.ts
  packages/shared/src/lib/auxiliary/explorer/utils/getExplorerEndpoint.ts
  packages/shared/src/lib/core/network/constants/default-base-token.constant.ts
  packages/shared/src/lib/core/network/constants/default-coin-type.constant.ts
  packages/shared/src/lib/core/network/constants/default-evm-network-configurations-for-stardust-network.constant.ts
  packages/shared/src/lib/core/network/constants/default-explorer-configs.constant.ts
  packages/shared/src/lib/core/network/constants/supported-network-id.constant.ts
  packages/shared/src/lib/core/network/enums/chain-id.enum.ts
Labels: type:feature

#2827 enhancement: dont await confirmation of eth transaction
  packages/shared/src/lib/core/activity/stores/all-account-activities.store.ts
  packages/shared/src/lib/core/activity/utils/evm/generateBaseEvmActivity.ts
  packages/shared/src/lib/core/network/classes/evm-network.class.ts
  packages/shared/src/lib/core/network/classes/isc-chain.class.ts
  packages/shared/src/lib/core/network/constants/average-block-time-in-seconds.constant.ts
  packages/shared/src/lib/core/network/constants/confirmation-threshold.constant.ts
  packages/shared/src/lib/core/network/constants/default-evm-network-configurations-for-stardust-network.constant.ts
  packages/shared/src/lib/core/network/constants/default-isc-chains-configurations.constant.ts
  packages/shared/src/lib/core/network/constants/failed-confirmation.constant.ts
  packages/shared/src/lib/core/network/constants/index.ts
  packages/shared/src/lib/core/network/interfaces/evm-network-configuration.interface.ts
  packages/shared/src/lib/core/network/interfaces/evm-network.interface.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-26-to-27.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-14-to-15.ts
  packages/shared/src/lib/core/transactions/types/local-evm-transaction.interface.ts
  packages/shared/src/lib/core/transactions/utils/buildLocalEvmTransactionFromBlockscoutTransaction.ts
  packages/shared/src/lib/core/wallet/actions/send/sendAndPersistTransactionFromEvm.ts
  packages/shared/src/lib/core/wallet/actions/sendSignedEvmTransaction.ts
  packages/shared/src/lib/core/wallet/utils/send/startEvmConfirmationPoll.ts
Labels: type:enhancement

#2845 fix: limit number of account network summary based on screen size
  packages/desktop/views/dashboard/wallet/panes/account-summary/AccountSummaryPane.svelte
Labels: type:fix

#2846 feat: adds noves indexer field to networks
  packages/shared/src/lib/core/network/constants/default-evm-network-configurations-for-stardust-network.constant.ts
  packages/shared/src/lib/core/network/constants/default-isc-chains-configurations.constant.ts
  packages/shared/src/lib/core/network/constants/default-noves-indexer-urls.constant.ts
  packages/shared/src/lib/core/network/constants/index.ts
  packages/shared/src/lib/core/network/constants/noves-translate-api-url.constant.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-27-to-28.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-14-to-15.ts
Labels: type:feature
