Repository bloomwalletio/bloom, pull requests merged in 2024-05, with the labels that each got.

#2410 feat: adds ERC721 collection support
  packages/shared/src/lib/core/nfts/interfaces/collection.interface.ts
  packages/shared/src/lib/core/nfts/stores/selected-account-collections.store.ts
  packages/shared/src/lib/core/nfts/utils/getCollectionFromNft.ts
Labels: type:feature

#2432 refactor: clean up all account nft stores
  packages/desktop/components/menus/CollectibleDetailsMenu.svelte
  packages/desktop/components/popup/popups/EvmActivityDetailsPopup.svelte
  packages/desktop/components/popup/popups/EvmTransactionFromDappPopup.svelte
  packages/desktop/components/popup/popups/ImportErc721TokenFormPopup.svelte
  packages/desktop/components/popup/popups/StardustActivityDetailsPopup.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/desktop/views/dashboard/collectibles/components/NftMediaAlert.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/AssetPillsForActivity.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityAssetSection.svelte
  packages/desktop/views/settings/views/collectibles/DownloadNftPermissions.svelte
  packages/desktop/views/settings/views/collectibles/MaxMediaSize.svelte
  packages/desktop/views/settings/views/collectibles/RefreshNftMedia.svelte
  packages/shared/src/components/activities/evm/EvmActivityInformation.svelte
  packages/shared/src/components/activities/stardust/StardustActivityInformation.svelte
  packages/shared/src/components/activities/stardust/info/StardustNftInformation.svelte
  packages/shared/src/lib/core/activity/actions/setAsyncStatusOfAccountActivities.ts
  packages/shared/src/lib/core/activity/utils/convertActvitiesToCsv.ts
  packages/shared/src/lib/core/activity/utils/getActivityTileAsset.ts
  packages/shared/src/lib/core/activity/utils/getTransactionAssets.ts
  packages/shared/src/lib/core/activity/utils/isVisibleActivity.ts
  packages/shared/src/lib/core/activity/utils/stardust/generateActivitiesFromBasicOutputs.ts
  packages/shared/src/lib/core/app/actions/registerNftDownloadEvents.ts
  packages/shared/src/lib/core/layer-2/utils/fetchIscAssetsForAccount.ts
  packages/shared/src/lib/core/nfts/actions/addNftsToDownloadQueue.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/nfts/actions/downloadNextNftInQueue.ts
  packages/shared/src/lib/core/nfts/actions/getNftByIdFromAllAccountNfts.ts
  packages/shared/src/lib/core/nfts/actions/index.ts
  packages/shared/src/lib/core/nfts/actions/interruptNftDownloadAfterTimeout.ts
  packages/shared/src/lib/core/nfts/actions/loadNftsForActiveProfile.ts
  packages/shared/src/lib/core/nfts/actions/setAccountNftsInAllAccountNfts.ts
  packages/shared/src/lib/core/nfts/actions/setNftInAllAccountNftsToUnspendable.ts
  packages/shared/src/lib/core/nfts/actions/updateAllAccountNfts.ts
  packages/shared/src/lib/core/nfts/actions/updateErc721NftOwnership.ts
  packages/shared/src/lib/core/nfts/actions/updateNftInAllAccountNfts.ts
  packages/shared/src/lib/core/nfts/stores/active-profile-nfts-per-account.store.ts
  packages/shared/src/lib/core/nfts/stores/all-account-nfts.store.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/selected-account-nfts.store.ts
  packages/shared/src/lib/core/nfts/utils/isNftOwnedByAnyAccount.ts
  packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts
  packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleSpentOutputEvent.ts
  packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleTransactionInclusionEvent.ts
  packages/shared/src/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/src/lib/core/utils/types/index.ts
  packages/shared/src/lib/core/utils/types/partial-with-id.type.ts
  packages/shared/src/lib/core/wallet/actions/burnNft.ts
  packages/shared/src/lib/core/wallet/actions/mintNft.ts
  packages/shared/src/lib/core/wallet/actions/send/signAndSendStardustTransaction.ts
  packages/shared/src/lib/core/wallet/actions/sendOutput.ts
Labels: type:refactor

#2407 fix: update collections on account change
  packages/desktop/views/dashboard/collectibles/components/CollectionsGalleryItem.svelte
  packages/shared/src/lib/core/nfts/stores/selected-account-collections.store.ts
Labels: type:fix

#2436 refactor: organise about window code into static class
  packages/desktop/lib/electron/constants/app-path.constant.ts
  packages/desktop/lib/electron/constants/default-web-preferences.constant.ts
  packages/desktop/lib/electron/menus/menu.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/lib/electron/windows/about.window.ts
Labels: type:refactor

#2411 fix: deconstructBip32Path sanitizing
  packages/shared/src/lib/core/account/utils/deconstructBip32Path.ts
Labels: type:fix, scope:security

#2439 fix: campaign card image size and polish
  packages/desktop/views/dashboard/campaigns/components/CampaignsGalleryItem.svelte
Labels: type:fix

#2438 fix: long nft images and nfts not showing in account index 0
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/shared/src/components/molecules/NftGalleryItem.svelte
  packages/shared/src/lib/core/nfts/stores/active-profile-nfts-per-account.store.ts
Labels: type:fix

#2453 refactor: clean up auto updater class
  packages/desktop/lib/electron/managers/auto-update.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
Labels: type:refactor

#2457 fix: total fiat calculation
  packages/shared/src/lib/core/token/stores/selected-account-tokens.store.ts
Labels: type:fix

#2449 refactor: remove async forEach
  packages/shared/src/lib/core/layer-2/actions/checkForUntrackedTokens.ts
  packages/shared/src/lib/core/layer-2/actions/fetchEvmBalancesForAccount.ts
  packages/shared/src/lib/core/layer-2/actions/pollEvmBalancesForAccount.ts
  packages/shared/src/lib/core/layer-2/utils/fetchEvmBalancesForAllAccounts.ts
Labels: type:refactor

#2455 fix: inefficient regex in preload
  packages/desktop/lib/electron/preloads/preload.ts
Labels: type:fix, scope:security

#2452 feat: persist NFT collections
  packages/desktop/components/popup/popups/ImportErc721TokenFormPopup.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectionsGalleryView.svelte
  packages/shared/src/lib/core/activity/utils/outputs/getIssuerFromNftOutput.ts
  packages/shared/src/lib/core/activity/utils/stardust/generateActivitiesFromBasicOutputs.ts
  packages/shared/src/lib/core/layer-2/utils/fetchIscAssetsForAccount.ts
  packages/shared/src/lib/core/nfts/actions/buildNftFromNftOutput.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/nfts/actions/index.ts
  packages/shared/src/lib/core/nfts/actions/loadNftsForActiveProfile.ts
  packages/shared/src/lib/core/nfts/actions/persistAndUpdateCollections.ts
  packages/shared/src/lib/core/nfts/interfaces/index.ts
  packages/shared/src/lib/core/nfts/interfaces/nft.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/persisted-collection.interface.ts
  packages/shared/src/lib/core/nfts/stores/active-profile-collections-per-account.store.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/persisted-collections.store.ts
  packages/shared/src/lib/core/nfts/stores/selected-account-collections.store.ts
  packages/shared/src/lib/core/nfts/types/collections.type.ts
  packages/shared/src/lib/core/nfts/types/index.ts
  packages/shared/src/lib/core/nfts/types/persisted-collections.type.ts
  packages/shared/src/lib/core/nfts/utils/buildNftFromPersistedErc721Nft.ts
  packages/shared/src/lib/core/nfts/utils/buildPersistedCollectionFromNft.ts
  packages/shared/src/lib/core/nfts/utils/index.ts
  packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts
  packages/shared/src/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/src/lib/core/wallet/actions/mintNft.ts
Labels: type:feature

#2465 ui: update network and token colors
  packages/shared/package.json
  packages/shared/src/components/avatars/NetworkAvatar.svelte
  packages/shared/src/components/avatars/TokenAvatar.svelte
  yarn.lock
Labels: type:ui

#2464 enhancement: delete profile while logged out
  packages/desktop/views/login/components/ProfileCardActionsMenu.svelte
  packages/desktop/views/settings/views/profile/DeleteProfile.svelte
  packages/shared/src/lib/contexts/settings/actions/deleteProfile.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#2466 refactor: simplify NFT collections data
  packages/desktop/components/popup/popups/ImportErc721TokenFormPopup.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionDetails.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionsGallery.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionsGalleryItem.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectionsGalleryView.svelte
  packages/shared/src/components/molecules/NftMedia.svelte
  packages/shared/src/lib/core/activity/utils/stardust/generateActivitiesFromBasicOutputs.ts
  packages/shared/src/lib/core/layer-2/utils/fetchIscAssetsForAccount.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/nfts/actions/index.ts
  packages/shared/src/lib/core/nfts/actions/loadNftsForActiveProfile.ts
  packages/shared/src/lib/core/nfts/actions/persistAndUpdateCollections.ts
  packages/shared/src/lib/core/nfts/actions/updatePersistedCollections.ts
  packages/shared/src/lib/core/nfts/interfaces/collection.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/index.ts
  packages/shared/src/lib/core/nfts/stores/active-profile-collections-per-account.store.ts
  packages/shared/src/lib/core/nfts/stores/active-profile-nfts-per-account.store.ts
  packages/shared/src/lib/core/nfts/stores/collections-search-term.store.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/persisted-collections.store.ts
  packages/shared/src/lib/core/nfts/types/collections.type.ts
  packages/shared/src/lib/core/nfts/types/index.ts
  packages/shared/src/lib/core/nfts/utils/isVisibleCollection.ts
  packages/shared/src/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts
  packages/shared/src/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/src/lib/core/wallet/actions/mintNft.ts
Labels: context:collectibles, type:refactor

#2467 fix: hide erc20 assets that do not have value from portfolio
  packages/shared/src/lib/core/token/actions/getAccountTokensForAccount.ts
Labels: type:fix

#2481 fix: dropdowns on FilterModal
  packages/desktop/components/modals/FilterModal.svelte
  packages/shared/package.json
  yarn.lock
Labels: type:fix, type:ui, scope:dependencies

#2468 fix: popup height and scrolling
  packages/desktop/components/popup/Popup.svelte
  packages/desktop/components/popup/PopupTemplate.svelte
  packages/desktop/views/dashboard/send-flow/views/SelectTokenView.svelte
Labels: type:fix

#2472 fix: don't override network with node info
  packages/desktop/components/popup/popups/NodeInfoPopup.svelte
  packages/desktop/lib/electron/apis/wallet.api.ts
  packages/desktop/views/onboarding/views/network-setup/views/CustomNetworkView.svelte
  packages/shared/src/components/organisms/NodeConfigurationForm.svelte
  packages/shared/src/lib/core/network/actions/getNodeInfoWhileLoggedOut.ts
  packages/shared/src/lib/core/profile-manager/api/getNodeInfo.ts
  packages/shared/src/lib/core/profile-manager/interfaces/api.interface.ts
  packages/shared/src/lib/core/profile/actions/active-profile/checkAndInitializeActiveProfileNetwork.ts
  packages/shared/src/lib/core/profile/actions/active-profile/checkAndUpdateActiveProfileNetwork.ts
  packages/shared/src/lib/core/profile/actions/active-profile/index.ts
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
  packages/shared/src/locales/en.json
  packages/shared/test/mocks/profile-manager.mock.ts
Labels: type:fix

#2486 chore: updates required node version in desktop README
  packages/desktop/README.md
Labels: type:chore

#2492 feat: improve account syncing
  packages/desktop/components/popup/popups/SyncAccountsPopup.svelte
  packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte
  packages/shared/src/lib/core/profile/constants/default-account-recovery-configuration.constant.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#2489 fix: allow customValue in NodeInput
  packages/shared/src/components/inputs/NodeInput.svelte
Labels: type:fix

#2490 fix: wrap text in LegalUpdatePopup
  packages/desktop/components/popup/popups/LegalUpdatePopup.svelte
Labels: type:fix

#2471 feat: add new iota testnet and iota testnet evm
  packages/desktop/features/onboarding.features.ts
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/views/dashboard/campaigns/components/CampaignHeader.svelte
  packages/desktop/views/onboarding/views/network-setup/NetworkSetupRouterView.svelte
  packages/desktop/views/onboarding/views/network-setup/network-setup-route.enum.ts
  packages/desktop/views/onboarding/views/network-setup/network-setup-router.ts
  packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/desktop/views/onboarding/views/network-setup/views/TestnetSelectionView.svelte
  packages/desktop/views/onboarding/views/network-setup/views/index.js
  packages/shared/src/components/avatars/NetworkAvatar.svelte
  packages/shared/src/components/avatars/TokenAvatar.svelte
  packages/shared/src/components/organisms/NodeConfigurationForm.svelte
  packages/shared/src/lib/auxiliary/icon/constants/default-network-icon.ts
  packages/shared/src/lib/auxiliary/icon/constants/default-token-icon.ts
  packages/shared/src/lib/contexts/onboarding/enums/onboarding-network-type.enum.ts
  packages/shared/src/lib/core/market/apis/coingecko.api.ts
  packages/shared/src/lib/core/network/apis/explorer.api.ts
  packages/shared/src/lib/core/network/constants/default-base-token.constant.ts
  packages/shared/src/lib/core/network/constants/default-bech32-hrp.constant.ts
  packages/shared/src/lib/core/network/constants/default-coin-type.constant.ts
  packages/shared/src/lib/core/network/constants/default-explorer-urls.constant.ts
  packages/shared/src/lib/core/network/constants/default-isc-chains-configurations.constant.ts
  packages/shared/src/lib/core/network/constants/default-network-metadata.constant.ts
  packages/shared/src/lib/core/network/constants/default-node-urls.constant.ts
  packages/shared/src/lib/core/network/constants/default-protocol.constant.ts
  packages/shared/src/lib/core/network/constants/faucet-urls.constant.ts
  packages/shared/src/lib/core/network/constants/supported-network-id.constant.ts
  packages/shared/src/lib/core/network/enums/chain-id.enum.ts
  packages/shared/src/lib/core/network/enums/stardust-network-name.enum.ts
  packages/shared/src/lib/core/network/tests/network.test.ts
  packages/shared/src/lib/core/network/utils/getExplorerApiNetworkName.ts
  packages/shared/src/lib/core/network/utils/getExplorerEndpoint.ts
  packages/shared/src/lib/core/network/utils/getExplorerUrl.ts
  packages/shared/src/lib/core/network/utils/index.ts
  packages/shared/src/lib/core/router/classes/router.class.ts
  packages/shared/src/lib/core/router/interfaces/index.ts
  packages/shared/src/lib/core/router/interfaces/router-event.interface.ts
  packages/shared/src/lib/core/router/interfaces/router.interface.ts
  packages/shared/src/lib/core/router/routers/app-router.ts
  packages/shared/src/lib/core/router/subrouters/login-router.ts
  packages/shared/src/lib/core/utils/api.ts
  packages/shared/src/lib/core/utils/string.ts
  packages/shared/src/lib/core/utils/url.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2494 fix: iota testnet constants
  packages/shared/src/lib/core/network/constants/default-explorer-urls.constant.ts
  packages/shared/src/lib/core/network/enums/chain-id.enum.ts
Labels: type:fix

#2488 fix: alignment if NFT with space as name
  packages/shared/src/components/molecules/NftGalleryItem.svelte
Labels: type:fix

#2502 fix: search more than one account
  packages/desktop/components/popup/popups/SyncAccountsPopup.svelte
  packages/desktop/views/onboarding/views/restore-profile/views/BalanceFinderView.svelte
  packages/shared/src/lib/core/profile/constants/default-account-recovery-configuration.constant.ts
Labels: type:fix

#2491 feat: add gas selector to transaction flow
  packages/desktop/components/popup/popups/EvmTransactionFromDappPopup.svelte
  packages/desktop/views/dashboard/send-flow/views/TransactionSummaryView.svelte
  packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionDetails.svelte
  packages/desktop/views/dashboard/send-flow/views/components/EvmTransactionSummary.svelte
  packages/desktop/views/dashboard/send-flow/views/components/SetTransactionFeeMenu.svelte
  packages/desktop/views/dashboard/send-flow/views/components/index.ts
  packages/shared/src/lib/auxiliary/blockscout/api/blockscout.api.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-stats.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/index.ts
  packages/shared/src/lib/core/layer-2/actions/canAccountMakeEvmTransaction.ts
  packages/shared/src/lib/core/layer-2/actions/setGasFee.ts
  packages/shared/src/lib/core/layer-2/constants/wei.constants.ts
  packages/shared/src/lib/core/layer-2/enums/gas-speed.enum.ts
  packages/shared/src/lib/core/layer-2/enums/index.ts
  packages/shared/src/lib/core/layer-2/interfaces/gas-prices-by-speed.interface.ts
  packages/shared/src/lib/core/layer-2/interfaces/index.ts
  packages/shared/src/lib/core/layer-2/utils/buildEvmTransactionData.ts
  packages/shared/src/lib/core/layer-2/utils/convertGweiToWei.ts
  packages/shared/src/lib/core/layer-2/utils/index.ts
  packages/shared/src/lib/core/network/classes/evm-network.class.ts
  packages/shared/src/lib/core/network/interfaces/evm-network.interface.ts
  packages/shared/src/lib/core/network/utils/isEvmNetwork.ts
  packages/shared/src/lib/core/wallet/utils/send/validateSendConfirmation.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2528 feat: adds Link in NotificationTile
  packages/shared/src/components/tiles/NotificationTile.svelte
Labels: type:feature

#2527 feat: highlight unread notifications
  packages/shared/src/components/tiles/NotificationTile.svelte
  packages/shared/src/lib/auxiliary/wallet-connect/notifications/classes/notificationsManager.class.ts
Labels: type:feature

#2515 feat: adds Ethereum logos
  packages/shared/package.json
  packages/shared/src/components/avatars/NetworkAvatar.svelte
  packages/shared/src/components/avatars/TokenAvatar.svelte
  packages/shared/src/lib/auxiliary/icon/constants/default-network-icon.ts
  packages/shared/src/lib/auxiliary/icon/constants/default-token-icon.ts
  yarn.lock
Labels: type:feature

#2506 enhancement: present smart contract inputs as `name: value`
  packages/desktop/components/popup/popups/EvmTransactionFromDappPopup.svelte
  packages/shared/src/components/activities/evm/info/EvmSmartContractInformation.svelte
Labels: type:enhancement

#2532 feat: mark notification as read if visible
  packages/desktop/views/dashboard/components/NotificationsButton.svelte
  packages/shared/package.json
  packages/shared/src/lib/auxiliary/wallet-connect/notifications/classes/notificationsManager.class.ts
  yarn.lock
Labels: type:feature

#2507 feat: adds restrictive content security policies
  packages/desktop/public/about.css
  packages/desktop/public/about.html
  packages/desktop/public/about.js
  packages/desktop/public/error.css
  packages/desktop/public/error.html
  packages/desktop/public/error.js
  packages/desktop/public/index.html
Labels: type:feature, scope:security

#2540 feat: notifications unread tab
  packages/desktop/views/dashboard/components/NotificationsButton.svelte
  packages/shared/src/components/avatars/NotificationAvatar.svelte
Labels: type:feature

#2541 enhancement: uses VirtualList in notifications
  packages/desktop/views/dashboard/components/NotificationsButton.svelte
  packages/shared/src/components/tiles/NotificationTile.svelte
Labels: type:enhancement

#2546 fix: remove hidden/scam nfts in collections
  packages/desktop/views/dashboard/collectibles/components/CollectionDetails.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionsGalleryItem.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectionsGalleryView.svelte
Labels: type:fix

#2537 enhancement: improve display of parsed smart contract data
  packages/desktop/components/evm-transactions/EvmSmartContractAlert.svelte
  packages/desktop/components/evm-transactions/index.ts
  packages/desktop/components/popup/popups/EvmTransactionFromDappPopup.svelte
  packages/shared/src/lib/core/layer-2/interfaces/parsed-contract-data.interface.ts
  packages/shared/src/lib/core/layer-2/utils/parseSmartContractDataFromTransactionData.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#2547 fix: add coingecko token images to be loaded in CSP
  packages/desktop/public/index.html
Labels: type:fix

#2554 feat: notification details popup
  packages/desktop/components/popup/Popup.svelte
  packages/desktop/components/popup/popups/EvmTransactionFromDappPopup.svelte
  packages/desktop/components/popup/popups/NotificationDetailsPopup.svelte
  packages/desktop/lib/auxiliary/popup/enums/popup-id.enum.ts
  packages/desktop/lib/auxiliary/popup/types/popup-component-map.type.ts
  packages/desktop/views/dashboard/components/NotificationsButton.svelte
  packages/shared/src/components/tiles/NotificationTile.svelte
  packages/shared/src/lib/core/wallet/types/token-transfer-data.type.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2552 fix: recover from skipped migrations
  packages/shared/src/lib/core/profile/actions/active-profile/loadPersistedProfileIntoActiveProfile.ts
  packages/shared/src/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/actions/checkAndMigrateOldLocalEvmTransactions.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-4-to-5.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-6-to-7.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-7-to-8.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-8-to-9.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-9-to-10.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-map.ts
  packages/shared/src/lib/core/profile/stores/profiles.store.ts
Labels: type:fix

#2558 fix: menu localization
  packages/desktop/lib/electron/menus/edit.menu.ts
  packages/desktop/lib/electron/menus/help.menu.ts
  packages/desktop/lib/electron/menus/menu-state.constant.ts
  packages/desktop/lib/electron/menus/menu.ts
  packages/desktop/lib/electron/menus/wallet.menu.ts
  packages/desktop/lib/helpers.ts
Labels: type:fix

#2559 fix: blurred QR code
  packages/shared/src/components/QR.svelte
Labels: type:fix

#2557 enhancement: disable hardware acceleration
  packages/desktop/lib/electron/processes/main.process.ts
Labels: type:enhancement

#2563 feat: enable campaign for iota profiles
  packages/desktop/views/dashboard/campaigns/components/CampaignHeader.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignsGalleryItem.svelte
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
Labels: type:feature
