Repository bloomwalletio/bloom, pull requests merged in 2024-02, with the labels that each got.

#1850 release: desktop 0.1.6
  packages/desktop/components/menus/CollectibleDetailsMenu.svelte
  packages/desktop/package.json
  packages/shared/src/components/molecules/NftGalleryItem.svelte
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
Labels: type:chore

#1734 chore: add primary pill with required tip
  packages/desktop/views/dashboard/drawers/dapp-config/components/AccountSelection.svelte
  packages/desktop/views/dashboard/drawers/dapp-config/components/Selection.svelte
  packages/shared/src/locales/en.json
Labels: type:enhancement

#1830 refactor: load URL directly in Transak window instead of using an iframe
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/preloads/transak.preload.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/public/transak.html
  packages/desktop/views/dashboard/buy-sell/components/TransakConnectionPanel.svelte
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/shared/src/lib/core/app/interfaces/managers/transak-manager.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/src/lib/core/ui/index.ts
  packages/shared/src/lib/core/ui/stores/index.ts
  packages/shared/src/lib/core/ui/stores/is-dashboard-sidebar-expanded.store.ts
  packages/shared/test/mocks/platform.mock.ts
Labels: type:fix, type:refactor

#1876 enhancement: show campaign total users
  packages/desktop/views/dashboard/campaigns/components/CampaignHeader.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignParticipantsPill.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignUsersPill.svelte
  packages/desktop/views/dashboard/campaigns/components/index.ts
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/shared/src/lib/contexts/campaigns/stores/campaign-leaderboards.store.ts
Labels: type:enhancement

#1881 enhancement: Transak connection panel
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/views/dashboard/buy-sell/components/TransakConnectionPanel.svelte
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/src/lib/auxiliary/transak/constants/index.ts
  packages/shared/src/lib/auxiliary/transak/constants/transak-production-widget-url.constant.ts
  packages/shared/src/lib/auxiliary/transak/constants/transak-staging-widget-url.constant.ts
  packages/shared/src/lib/auxiliary/transak/constants/transak-widget-url.constant.ts
  packages/shared/src/lib/auxiliary/transak/enums/index.ts
  packages/shared/src/lib/auxiliary/transak/enums/transak-connection-status.enum.ts
  packages/shared/src/lib/auxiliary/transak/index.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#1897 fix: Transak opening multiple windows
  packages/desktop/lib/electron/managers/transak.manager.ts
Labels: type:fix

#1932 release: desktop 0.1.7
  packages/desktop/package.json
Labels: type:chore

#1935 ui: rebrand manage voting power pane and popups
  packages/desktop/components/ProposalsDetails.svelte
  packages/desktop/components/index.ts
  packages/desktop/components/menus/index.ts
  packages/desktop/components/popup/PopupTemplate.svelte
  packages/desktop/components/popup/popups/ManageVotingPowerPopup.svelte
  packages/desktop/components/popup/popups/RevotePopup.svelte
  packages/desktop/components/popup/popups/VotingPowerToZeroPopup.svelte
  packages/desktop/views/dashboard/governance/components/ManageVotingPowerMenu.svelte
  packages/desktop/views/dashboard/governance/components/ManageVotingPowerPane.svelte
  packages/desktop/views/dashboard/governance/components/index.ts
  packages/desktop/views/dashboard/governance/views/GovernanceDashboardView.svelte
  packages/shared/src/components/inputs/InputContainer.svelte
  packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte
  packages/shared/src/lib/contexts/governance/actions/setVotingPower.ts
Labels: type:refactor, type:ui

#1936 chore: remove unused comp
  packages/shared/src/components/boxes/CopyableBox.svelte
  packages/shared/src/components/boxes/index.ts
Labels: type:chore

#1934 fix: AccountSwitcher scroll
  packages/desktop/components/AccountSwitcher.svelte
  packages/shared/package.json
  yarn.lock
Labels: type:fix

#1942 Chore: rebrand nodeauthrequired popop
  packages/desktop/components/popup/popups/AddNodePopup.svelte
  packages/desktop/components/popup/popups/NodeAuthRequiredPopup.svelte
  packages/desktop/views/onboarding/views/network-setup/views/CustomNetworkView.svelte
  packages/shared/src/components/helpers/getTabItems.ts
  packages/shared/src/components/molecules/NodeAuthTab.svelte
  packages/shared/src/components/molecules/index.ts
  packages/shared/src/components/organisms/NodeConfigurationForm.svelte
  packages/shared/src/components/organisms/index.ts
  packages/shared/src/locales/en.json
Labels: type:ui

#1948 refactor: rebrand ProposalStatusPill
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/desktop/views/governance/components/ProposalStatusInfo.svelte
  packages/desktop/views/governance/components/ProposalStatusPill.svelte
  packages/desktop/views/governance/components/index.ts
  packages/shared/src/components/pills/ProposalStatusPill.svelte
  packages/shared/src/components/pills/index.js
Labels: type:refactor

#1951 chore: rebrand stop voting pop-up
  packages/desktop/components/popup/popups/StopVotingPopup.svelte
Labels: type:chore

#1925 enhancement: polish Transak payment provider flows
  packages/desktop/features/buy-sell.features.ts
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/shared/src/locales/en.json
Labels: type:enhancement

#1947 refactor: rebrand ProposalStatusTimelineTooltip
  packages/desktop/components/ProposalStatusTimelineTooltip.svelte
  packages/desktop/components/index.ts
  packages/desktop/features/governance.features.ts
  packages/desktop/views/governance/components/ProposalStatusInfo.svelte
  packages/desktop/views/governance/components/ProposalStatusTimelineTooltip.svelte
  packages/desktop/views/governance/components/index.ts
  packages/shared/src/locales/en.json
Labels: type:refactor

#1887 Chore: update tailwindcss & cleanup safelist
  packages/desktop/views/components/Background.svelte
  packages/desktop/views/components/ButtonTile.svelte
  packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/shared/package.json
  packages/shared/src/components/Spinner.svelte
  packages/shared/src/components/StrengthMeter.svelte
  packages/shared/src/components/Text.svelte
  packages/shared/src/components/Tooltip.svelte
  packages/shared/src/components/badges/StrongholdBadge.svelte
  packages/shared/src/components/boxes/Box.svelte
  packages/shared/src/components/enums/font-weight.enum.ts
  packages/shared/src/components/inputs/AmountInput.svelte
  packages/shared/src/components/inputs/Input.svelte
  packages/shared/src/components/inputs/InputContainer.svelte
  packages/shared/src/components/inputs/TextInput.svelte
  packages/shared/src/components/inputs/TokenAmountInput.svelte
  packages/shared/src/components/inputs/TokenAmountWithSliderInput.svelte
  packages/shared/tailwind.config.js
  yarn.lock
Labels: scope:dependencies

#1967 refactor: rebrand ProposalQuestion
  packages/desktop/components/index.ts
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/desktop/views/governance/components/ProposalQuestion.svelte
  packages/desktop/views/governance/components/index.ts
Labels: type:refactor

#1970 refactor: rebrand ProposalDetailsMenu
  packages/desktop/components/menus/ProposalDetailsMenu.svelte
  packages/shared/src/locales/en.json
Labels: type:refactor

#1972 refactor: rebrand ProposalAnswer
  packages/desktop/components/ProposalAnswer.svelte
  packages/shared/package.json
  yarn.lock
Labels: type:refactor

#1974 refactor: rebrand ProposalsDetails
  packages/desktop/components/ProposalListDetails.svelte
  packages/desktop/components/index.ts
  packages/desktop/views/dashboard/governance/views/GovernanceDashboardView.svelte
  packages/shared/src/lib/contexts/governance/interfaces/index.ts
  packages/shared/src/lib/contexts/governance/interfaces/proposal-list-details.interface.ts
Labels: type:refactor

#1977 chore: rebrand GovernanceDashboardView
  packages/desktop/views/dashboard/governance/views/GovernanceDashboardView.svelte
Labels: type:chore

#1973 refactor: rebrand MarkdownBlock
  packages/desktop/App.svelte
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/shared/package.json
  packages/shared/src/components/molecules/MarkdownBlock.svelte
  packages/shared/src/components/molecules/index.ts
  packages/shared/src/components/molecules/markdown-renderers/LinkBlock.svelte
  packages/shared/src/components/molecules/markdown-renderers/ParagraphBlock.svelte
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  yarn.lock
Labels: type:refactor

#1985 refactor: rebrand ProposalDetailsView
  packages/desktop/views/dashboard/governance/components/index.ts
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalAccountVotingPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalDetailsPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalInformationPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalQuestionListPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/index.ts
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
Labels: type:refactor

#2002 feat: explorer api pagination
  packages/shared/src/lib/auxiliary/blockscout/api/blockscout.api.ts
  packages/shared/src/lib/auxiliary/blockscout/api/index.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-api.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-asset-metadata.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-asset.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-transaction.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/index.ts
  packages/shared/src/lib/core/layer-2/actions/checkForUntrackedTokens.ts
  packages/shared/src/lib/core/network/classes/evm-explorer-api.class.ts
  packages/shared/src/lib/core/network/classes/index.ts
  packages/shared/src/lib/core/network/interfaces/explorer-api.interface.ts
  packages/shared/src/lib/core/network/interfaces/explorer-asset.interface.ts
  packages/shared/src/lib/core/network/interfaces/index.ts
  packages/shared/src/lib/core/nfts/actions/checkForUntrackedNfts.ts
  packages/shared/src/lib/core/tide/apis/tide.api.ts
  packages/shared/src/lib/core/utils/api.ts
  packages/shared/src/lib/core/utils/types/api.types.ts
  packages/shared/src/lib/core/utils/types/index.ts
  packages/shared/src/lib/core/utils/url.ts
Labels: type:feature

#2001 fix: adds checkbox highlight in ConnectionRequestDrawer
  packages/desktop/views/dashboard/drawers/dapp-config/views/ConnectionRequestDrawer.svelte
Labels: type:fix

#2008 feat: persist evm blockscout transactions
  packages/shared/src/lib/auxiliary/blockscout/api/blockscout.api.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-transaction.interface.ts
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
  packages/shared/src/lib/core/transactions/actions/fetchAndPersistTransactionsForAccounts.ts
  packages/shared/src/lib/core/transactions/actions/index.ts
  packages/shared/src/lib/core/transactions/stores/index.ts
  packages/shared/src/lib/core/transactions/stores/transactions.store.ts
Labels: type:feature

#2013 refactor: store local evm transactions in same store as blockscout evm transactions
  packages/desktop/components/popup/popups/SyncAccountsPopup.svelte
  packages/shared/src/lib/core/activity/actions/generateAndStoreActivitiesForAccount.ts
  packages/shared/src/lib/core/activity/actions/generateAndStoreActivitiesForAllAccounts.ts
  packages/shared/src/lib/core/activity/stores/persisted-transactions.store.ts
  packages/shared/src/lib/core/activity/utils/generateActivitiesFromChains.ts
  packages/shared/src/lib/core/nfts/actions/loadNftsForActiveProfile.ts
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
  packages/shared/src/lib/core/profile/actions/profiles/removeAllProfileData.ts
  packages/shared/src/lib/core/wallet/actions/send/signAndSendTransactionFromEvm.ts
Labels: type:refactor

#2016 enhancement: Transak getURL input validation
  packages/desktop/lib/electron/managers/transak.manager.ts
Labels: type:enhancement

#2015 feat: generate activities from persisted transactions
  packages/shared/src/lib/auxiliary/blockscout/enums/blockscout-transaction-status.enum.ts
  packages/shared/src/lib/auxiliary/blockscout/enums/index.ts
  packages/shared/src/lib/auxiliary/blockscout/index.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-transaction.interface.ts
  packages/shared/src/lib/core/activity/utils/generateActivitiesFromChains.ts
  packages/shared/src/lib/core/activity/utils/generateActivityFromPeristedTransaction.ts
  packages/shared/src/lib/core/transactions/index.ts
  packages/shared/src/lib/core/transactions/stores/transactions.store.ts
  packages/shared/src/lib/core/transactions/types/index.ts
  packages/shared/src/lib/core/transactions/types/persisted-transaction.type.ts
  packages/shared/src/lib/core/transactions/utils/buildPersistedEvmTransactionFromBlockscoutTransaction.ts
  packages/shared/src/lib/core/transactions/utils/index.ts
Labels: type:feature

#2018 fix: voting power locales
  packages/shared/src/locales/en.json
Labels: type:fix
