Repository bloomwalletio/bloom, pull requests merged in 2024-06, with the labels that each got.

#2595 release: desktop 1.0.4
  packages/desktop/features/onboarding.features.ts
  packages/desktop/package.json
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/migrations/actions/addDefaultIscChainsToIotaProfiles.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-19-to-20.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-20-to-21.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-9-to-10.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-map.ts
Labels: type:chore

#2598 feat: geofence transak in uk
  packages/desktop/App.svelte
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/desktop/views/settings/views/advanced/ToggleFeatures.svelte
  packages/shared/src/lib/auxiliary/country/actions/getAndUpdateCountryCode.ts
  packages/shared/src/lib/auxiliary/country/actions/index.ts
  packages/shared/src/lib/auxiliary/country/api/country.api.ts
  packages/shared/src/lib/auxiliary/country/api/index.ts
  packages/shared/src/lib/auxiliary/country/index.ts
  packages/shared/src/lib/auxiliary/country/stores/country-code.store.ts
  packages/shared/src/lib/auxiliary/country/stores/index.ts
  packages/shared/src/lib/core/app/interfaces/app-parameters.interface.ts
  packages/shared/src/lib/core/app/json/configurable-app-parameters.json
  packages/shared/src/lib/features/utils/index.ts
  packages/shared/src/lib/features/utils/isFeatureGeoFenced.ts
Labels: type:feature

#2604 fix: bigIntLikeToBigInt coverage
  packages/shared/src/lib/core/utils/convert.ts
  packages/shared/src/lib/core/utils/tests/convert.test.ts
Labels: type:fix

#2601 enhancement: adds total balance to AccountSwitcher
  packages/desktop/components/AccountSwitcher.svelte
  packages/desktop/views/dashboard/components/Breadcrumbs.svelte
  packages/shared/package.json
  packages/shared/src/locales/en.json
  yarn.lock
Labels: type:enhancement

#2587 chore: removes sass
  package.json
  packages/desktop/App.svelte
  packages/desktop/components/TitleBar.svelte
  packages/desktop/components/filter/FilterItem.svelte
  packages/desktop/components/popup/popups/ErrorLogPopup.svelte
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/dashboard/components/Navbar.svelte
  packages/desktop/views/dashboard/governance/components/ProposalCard.svelte
  packages/desktop/views/dashboard/wallet/Wallet.svelte
  packages/desktop/views/login/views/SelectProfileView.svelte
  packages/desktop/views/onboarding/views/WelcomeView.svelte
  packages/shared/package.json
  packages/shared/src/components/Tooltip.svelte
  packages/shared/src/components/inputs/Dropdown.svelte
  packages/shared/src/components/inputs/index.ts
  packages/shared/src/components/molecules/DappInfo.svelte
  packages/shared/src/components/molecules/MediaIcon.svelte
  packages/shared/src/components/tiles/ShimmerClaimingAccountTile.svelte
  packages/shared/src/lib/core/utils/interfaces/dropdown-item.interface.ts
  packages/shared/src/lib/core/utils/interfaces/index.ts
  packages/shared/src/style/style.css
  packages/shared/tailwind.config.js
  yarn.lock
Labels: type:chore, scope:dependencies

#2624 fix: improve handling of transaction from wallet connect
  packages/desktop/components/popup/popups/EvmTransactionFromDappPopup.svelte
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/eth_transaction.handler.ts
  packages/shared/src/lib/core/isc/abis/isc-magic-contract-accounts.abi.ts
  packages/shared/src/lib/core/layer-2/utils/parseSmartContractDataFromTransactionData.ts
  packages/shared/src/lib/core/utils/convert.ts
Labels: type:fix

#2629 enhancement: get token metadata and prices for iota evm chain
  packages/desktop/App.svelte
  packages/shared/src/lib/core/market/actions/getAndUpdateMarketPrices.ts
  packages/shared/src/lib/core/market/actions/getAndUpdateShimmerEvmTokensMetadata.ts
  packages/shared/src/lib/core/market/actions/getAndUpdateTokensMetadataFromCoinGecko.ts
  packages/shared/src/lib/core/market/actions/index.ts
  packages/shared/src/lib/core/market/apis/coingecko.api.ts
  packages/shared/src/lib/core/market/enums/coingecko-network-id.enum.ts
  packages/shared/src/lib/core/network/classes/isc-chain.class.ts
Labels: type:enhancement

#2646 enhancement: improve display of incompatible profile on dapp pairing
  packages/desktop/views/dashboard/drawers/dapp-config/components/UnsupportedDappHint.svelte
  packages/desktop/views/dashboard/drawers/dapp-config/views/ConfirmConnectionDrawer.svelte
  packages/desktop/views/dashboard/drawers/dapp-config/views/ConnectionRequestDrawer.svelte
  packages/shared/src/locales/en.json
Labels: type:enhancement

#2650 fix: delay on proposal status by initialising stardust node info
  packages/shared/src/lib/core/network/classes/stardust-network.class.ts
Labels: type:fix

#2649 fix: update coin gecko network id for iota
  packages/shared/src/lib/core/market/enums/coingecko-network-id.enum.ts
Labels: type:fix

#2662 enhancement: modify dashboard UI so that it supports 3 networks ethereum
  packages/desktop/components/AccountSwitcher.svelte
  packages/desktop/components/menus/AccountActionsMenu.svelte
  packages/desktop/components/popup/popups/ExportActivitiesPopup.svelte
  packages/desktop/views/dashboard/drawers/dapp-config/components/AccountSelection.svelte
  packages/desktop/views/dashboard/wallet/panes/account-summary/AccountSummaryPane.svelte
  packages/desktop/views/dashboard/wallet/panes/account-summary/components/AccountNetworkActionsMenu.svelte
  packages/desktop/views/dashboard/wallet/panes/account-summary/components/AccountNetworkSummary.svelte
  packages/desktop/views/dashboard/wallet/panes/account-summary/components/AccountSummary.svelte
  packages/shared/package.json
  packages/shared/src/lib/core/app/constants/external-allowed-links.constant.ts
  packages/shared/src/lib/core/token/stores/selected-account-tokens.store.ts
  packages/shared/src/locales/en.json
  yarn.lock
Labels: type:enhancement

#2658 feat: adds country, accounts count and profile count in analytics
  packages/desktop/lib/electron/managers/third-party-profiles.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/lib/electron/utils/analytics.utils.ts
  packages/desktop/lib/electron/utils/storage.utils.ts
  packages/shared/src/lib/auxiliary/country/actions/getAndUpdateCountryCode.ts
  packages/shared/src/lib/auxiliary/country/api/country.api.ts
  packages/shared/src/lib/core/utils/api.ts
Labels: type:feature

#2673 fix: dapp connections for multiple evm chains
  packages/shared/src/lib/auxiliary/wallet-connect/utils/buildDefaultNamespaces.ts
Labels: type:fix

#2675 fix: round token in formatter and truncate symbol if to long
  packages/shared/src/lib/core/token/utils/formatTokenAmount.ts
Labels: type:fix

#2676 feat: handle switch ethereum chain
  packages/shared/src/lib/auxiliary/wallet-connect/constants/general-supported-methods.constant.ts
  packages/shared/src/lib/auxiliary/wallet-connect/enums/rpc-method.enum.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/index.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/onSessionRequest.handler.ts
  packages/shared/src/lib/auxiliary/wallet-connect/handlers/wallet_switchEthereumChain.handler.ts
Labels: type:feature

#2678 fix: prevent creating duplicate wc sessions
  packages/shared/src/lib/auxiliary/wallet-connect/actions/approveSession.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/connectToDapp.ts
Labels: type:fix

#2679 fix: get network name form evm networks too
  packages/shared/src/lib/core/network/actions/getNameFromNetworkId.ts
Labels: type:fix
