Repository bloomwalletio/bloom, pull requests merged in 2024-08, with the labels that each got.

#2781 fix: L1 -> L2 Nft gas fee estimate
  packages/shared/src/lib/core/network/classes/isc-chain.class.ts
Labels: type:fix

#2759 feat: selectable quotation and dynamic button text
  packages/desktop/views/dashboard/buy-sell/components/TransakCryptoCurrencyAmountTile.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakExchangePanel.svelte
  packages/shared/src/locales/en.json
Labels: type:feature

#2760 feat: localise payment methods, improve icons and fix iframe width/border
  packages/desktop/components/popup/popups/TransakFramePopup.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakExchangePanel.svelte
  packages/shared/package.json
  packages/shared/src/lib/auxiliary/transak/actions/updateTransakFiatCurrencies.ts
  packages/shared/src/lib/auxiliary/transak/stores/transak-fiat-currencies.store.ts
  packages/shared/src/locales/en.json
  yarn.lock
Labels: type:feature, type:fix

#2786 fix: show warning when users attempt to create account with deprecated ledger app version
  packages/desktop/components/StatusTile.svelte
  packages/desktop/components/popup/profileAuthPopups/ConnectLedgerPopup.svelte
  packages/desktop/views/dashboard/components/LedgerStatusTile.svelte
  packages/desktop/views/onboarding/views/create-from-ledger/views/ConnectLedgerView.svelte
  packages/desktop/views/onboarding/views/create-from-ledger/views/components/StepCard.svelte
  packages/desktop/views/onboarding/views/create-from-ledger/views/components/index.ts
  packages/shared/src/components/enums/ledger-illustration-variant.enum.ts
  packages/shared/src/components/molecules/LedgerStatusIllustration.svelte
  packages/shared/src/lib/core/ledger/actions/checkOrConnectLedger.ts
  packages/shared/src/lib/core/ledger/constants/index.ts
  packages/shared/src/lib/core/ledger/constants/minimum-supported-iota-ledger-app.constant.ts
  packages/shared/src/lib/core/ledger/constants/minimum-supported-ledger-app-versions.constant.ts
  packages/shared/src/lib/core/ledger/enums/ledger-connection-state.enum.ts
  packages/shared/src/lib/core/ledger/interfaces/index.ts
  packages/shared/src/lib/core/ledger/interfaces/ledger-connection-app-state.interface.ts
  packages/shared/src/lib/core/ledger/stores/index.ts
  packages/shared/src/lib/core/ledger/stores/ledger-connection-app-state.store.ts
  packages/shared/src/lib/core/ledger/stores/ledger-connection-state.store.ts
  packages/shared/src/lib/core/ledger/utils/determineLedgerConnectionAppState.ts
  packages/shared/src/lib/core/ledger/utils/determineLedgerConnectionState.ts
  packages/shared/src/lib/core/ledger/utils/index.ts
  packages/shared/src/lib/core/ledger/utils/isLedgerAppVersionSupported.ts
  packages/shared/src/lib/core/utils/index.ts
  packages/shared/src/lib/core/utils/version.ts
  packages/shared/src/locales/en.json
Labels: type:fix

#2790 ui: update wording of choose networks on onboarding
  packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/shared/package.json
  packages/shared/src/locales/en.json
  yarn.lock
Labels: type:ui
