Repository bloomwalletio/bloom, pull requests merged in 2024-03, with the labels that each got.

#2049 fix: MarketCurrency in Transak
  packages/desktop/lib/electron/managers/transak.manager.ts
Labels: type:fix

#2064 ui: polish title in governance dashboard
  packages/desktop/views/dashboard/governance/components/ProposalList.svelte
  packages/desktop/views/dashboard/governance/views/GovernanceDashboardView.svelte
  packages/shared/src/locales/en.json
Labels: type:ui

#2067 ui: improve proposal details ui
  packages/desktop/views/dashboard/governance/components/ProposalList.svelte
  packages/desktop/views/dashboard/governance/components/ProposalListDetails.svelte
  packages/desktop/views/dashboard/governance/components/ProposalListMenu.svelte
  packages/desktop/views/dashboard/governance/components/index.ts
  packages/desktop/views/dashboard/governance/views/GovernanceDashboardView.svelte
  packages/shared/src/locales/en.json
Labels: type:ui

#2075 fix: Transak currency validation and defaultCryptoAmount
  packages/desktop/lib/electron/managers/transak.manager.ts
Labels: type:fix

#2077 feat: show projected votes as a secondary striped bar
  packages/desktop/views/dashboard/governance/components/ProposalAnswer.svelte
  packages/desktop/views/dashboard/governance/components/ProposalQuestion.svelte
  packages/shared/src/lib/auxiliary/notification/actions/showNotification.ts
  packages/shared/src/lib/contexts/governance/interfaces/index.ts
  packages/shared/src/lib/contexts/governance/interfaces/proposal-answer-percentage.interface.ts
  packages/shared/src/lib/contexts/governance/interfaces/proposal-answer-percentages.interface.ts
  packages/shared/src/lib/contexts/governance/utils/getPercentagesFromAnswerStatuses.ts
  packages/shared/src/lib/contexts/governance/utils/getProjectedPercentages.ts
  packages/shared/src/lib/contexts/governance/utils/index.ts
  packages/shared/src/lib/contexts/governance/utils/tests/getPercentagesFromAnswerStatuses.test.ts
  packages/shared/src/lib/core/profile/utils/isLedgerProfile.ts
Labels: type:feature

#2085 enhancement: show ProposalAnswer additional info in a Popup
  packages/desktop/views/dashboard/governance/components/ProposalAnswer.svelte
Labels: type:enhancement

#2095 feat: generate activity from token transfers
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityFeeSection.svelte
  packages/shared/src/lib/auxiliary/blockscout/api/blockscout.api.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-token-info.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/blockscout-token-transfer.interface.ts
  packages/shared/src/lib/auxiliary/blockscout/interfaces/index.ts
  packages/shared/src/lib/auxiliary/blockscout/types/blockscout-token-transfer.type.ts
  packages/shared/src/lib/auxiliary/blockscout/types/index.ts
  packages/shared/src/lib/core/activity/utils/evm/generateEvmActivityFromPersistedTransaction.ts
  packages/shared/src/lib/core/activity/utils/evm/generateEvmTokenTransferActivityFromBlockscoutTokenTransfer.ts
  packages/shared/src/lib/core/activity/utils/evm/index.ts
  packages/shared/src/lib/core/token/utils/formatTokenAmountBestMatch.ts
  packages/shared/src/lib/core/transactions/actions/fetchAndPersistTransactionsForAccounts.ts
  packages/shared/src/lib/core/transactions/stores/transactions.store.ts
  packages/shared/src/lib/core/transactions/types/persisted-transaction.type.ts
Labels: type:enhancement

#2098 enhancement: project votes for open phase
  packages/desktop/views/dashboard/governance/components/ProposalAnswer.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProjectionTogglePane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalQuestionListPane.svelte
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/shared/src/lib/contexts/governance/interfaces/proposal-answer-percentage.interface.ts
  packages/shared/src/lib/contexts/governance/utils/getPercentagesFromAnswerStatuses.ts
Labels: type:enhancement

#2100 fix: info buttons on proposal questions and answers
  packages/desktop/views/dashboard/governance/components/ProposalAnswer.svelte
  packages/desktop/views/dashboard/governance/components/ProposalQuestion.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalDetailsPane.svelte
  packages/shared/src/locales/en.json
Labels: type:fix

#2092 feat: adds circulating supply in Governance
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalAccountVotingPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalDetailsPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalInformationPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/QuorumProgress.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/index.ts
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/shared/src/lib/contexts/governance/utils/getCirculatingSupplyVotedPercentage.ts
  packages/shared/src/lib/contexts/governance/utils/index.ts
  packages/shared/src/lib/core/network/apis/explorer.api.ts
  packages/shared/src/lib/core/network/apis/index.ts
  packages/shared/src/lib/core/network/constants/default-explorer-api-base-url.constant.ts
  packages/shared/src/lib/core/network/enums/explorer-api-endpoint.enum.ts
  packages/shared/src/lib/core/network/enums/index.ts
  packages/shared/src/lib/core/network/interfaces/explorer-api-network.interface.ts
  packages/shared/src/lib/core/network/interfaces/explorer-api-networks.interface.ts
  packages/shared/src/lib/core/network/interfaces/index.ts
  packages/shared/src/lib/core/network/interfaces/protocol.interface.ts
  packages/shared/src/lib/core/network/utils/getExplorerApiNetworkName.ts
  packages/shared/src/lib/core/network/utils/index.ts
  packages/shared/src/lib/core/profile/actions/active-profile/index.ts
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
  packages/shared/src/lib/core/profile/actions/active-profile/updateCirculatingSupplyForActiveProfile.ts
  packages/shared/src/lib/core/utils/number.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2105 release: desktop 0.1.9
  packages/desktop/package.json
  packages/desktop/views/dashboard/governance/components/proposal-details/QuorumProgress.svelte
  packages/shared/src/lib/contexts/governance/utils/getCirculatingSupplyVotedPercentage.ts
  packages/shared/src/locales/da.json
  packages/shared/src/locales/de.json
  packages/shared/src/locales/hr.json
  yarn.lock
Labels: type:chore

#2111 chore: adds production & staging key for Transak in build action
  .github/workflows/reusable_build.yml
Labels: type:chore

#2110 fix: check valid preload path for Transak
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/views/dashboard/buy-sell/components/TransakWindowPlaceholder.svelte
  packages/desktop/views/dashboard/buy-sell/components/index.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/locales/en.json
Labels: type:fix

#2053 Fix: snyk
  packages/desktop/package.json
  patches/electron-updater+6.1.8.patch
  yarn.lock
Labels: scope:dependencies

#2118 fix: hide Transak window when drawer is open
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
Labels: type:fix

#2119 enhancement: default amount to 100 dollars with conversion to each fiat currency
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/src/lib/core/app/interfaces/transak-window-data.interface.ts
Labels: type:enhancement

#2112 fix: show quorum percentage during commencement phase
  packages/shared/src/lib/contexts/governance/utils/getCirculatingSupplyVotedPercentage.ts
Labels: type:fix

#2140 chore: update electron
  packages/desktop/package.json
  yarn.lock
Labels: scope:dependencies

#2158 fix: quorum calculation and add projected quorum
  packages/desktop/views/dashboard/governance/components/proposal-details/ProposalQuestionListPane.svelte
  packages/desktop/views/dashboard/governance/components/proposal-details/QuorumProgress.svelte
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/shared/src/lib/contexts/governance/utils/getCirculatingSupplyVotedPercentage.ts
  packages/shared/src/lib/core/utils/number.ts
Labels: type:enhancement, type:fix

#2154 feat: adds dark mode in Transak
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/lib/core/app/interfaces/transak-window-data.interface.ts
Labels: type:feature

#2160 chore: increment desktop version to `0.1.10`
  packages/desktop/package.json
Labels: type:chore

#2175 feat: add import profiles to electron menu
  packages/desktop/lib/electron/menus/menu-state.constant.ts
  packages/desktop/lib/electron/menus/menu.ts
  packages/desktop/lib/helpers.ts
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2184 feat: adds Spinner when Transak window has not loaded yet
  packages/desktop/features/buy-sell.features.ts
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/preloads/transak.preload.ts
  packages/desktop/views/dashboard/buy-sell/components/TransakWindowPlaceholder.svelte
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
Labels: type:feature

#2185 ui: polish transak
  packages/desktop/components/AccountSwitcher.svelte
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/views/dashboard/buy-sell/components/TransakAccountPanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakConnectionPanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakWindowPlaceholder.svelte
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/desktop/views/dashboard/components/Breadcrumbs.svelte
  packages/desktop/views/dashboard/wallet/panes/account-summary/components/AccountSummary.svelte
  packages/shared/assets/logos/transak.png
  packages/shared/assets/logos/transak.svg
  packages/shared/package.json
  yarn.lock
Labels: type:ui

#2189 Release: desktop 0.1.11
  packages/desktop/package.json
Labels: type:chore

#2201 enhancement: ImportProfileTile
  packages/desktop/components/ImportProfileTile.svelte
  packages/desktop/components/popup/popups/ImportProfilesFromThirdPartyPopup.svelte
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/managers/third-party-profiles.manager.ts
  packages/shared/src/lib/core/network/utils/getNetworkIdFromOnboardingNetworkType.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement, type:ui

#2207 enhancement: detect apps to import
  packages/desktop/components/ImportProfileTile.svelte
  packages/desktop/components/popup/PopupTemplate.svelte
  packages/desktop/components/popup/popups/ImportProfilesFromThirdPartyPopup.svelte
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/managers/third-party-profiles.manager.ts
  packages/desktop/views/import-third-party-profiles/ImportThirdPartyProfilesRouterView.svelte
  packages/desktop/views/import-third-party-profiles/import-third-party-profiles-route.enum.ts
  packages/desktop/views/import-third-party-profiles/import-third-party-profiles.router.ts
  packages/desktop/views/import-third-party-profiles/index.ts
  packages/desktop/views/import-third-party-profiles/views/ImportProfilesView.svelte
  packages/desktop/views/import-third-party-profiles/views/SelectAppsView.svelte
  packages/desktop/views/import-third-party-profiles/views/index.ts
  packages/desktop/views/onboarding/OnboardingRouterView.svelte
  packages/desktop/views/onboarding/onboarding-router.ts
  packages/desktop/views/onboarding/views/WelcomeView.svelte
  packages/desktop/views/onboarding/views/import-third-party/ImportThirdPartyProfilesView.svelte
  packages/desktop/views/onboarding/views/import-third-party/index.js
  packages/desktop/views/onboarding/views/index.js
  packages/shared/src/lib/auxiliary/third-party/actions/getThirdPartyPersistedProfiles.ts
  packages/shared/src/lib/auxiliary/third-party/actions/updateThirdPartyProfilesStore.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#2212 feat: enable ability for user to toggle features
  packages/desktop/features/settings.features.ts
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/desktop/views/settings/views/advanced/DeveloperToggle.svelte
  packages/desktop/views/settings/views/advanced/ToggleFeatures.svelte
  packages/desktop/views/settings/views/advanced/advanced-settings.constant.js
  packages/desktop/views/settings/views/advanced/index.js
  packages/shared/src/lib/contexts/onboarding/helpers/convertOnboardingProfileToPersistedProfile.ts
  packages/shared/src/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/src/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-8-to-9.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-4-to-5.ts
  packages/shared/src/lib/core/router/enums/settings/advanced-settings-route.enum.ts
  packages/shared/src/lib/features/interfaces/settings-features.interface.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2070 feat: import data from 3rd party apps
  packages/desktop/components/ImportProfileTile.svelte
  packages/desktop/components/index.ts
  packages/desktop/components/popup/Popup.svelte
  packages/desktop/components/popup/PopupTemplate.svelte
  packages/desktop/components/popup/popups/ImportProfilesFromThirdPartyPopup.svelte
  packages/desktop/lib/auxiliary/popup/enums/popup-id.enum.ts
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/managers/keychain.manager.ts
  packages/desktop/lib/electron/managers/pincode.manager.ts
  packages/desktop/lib/electron/managers/third-party-profiles.manager.ts
  packages/desktop/lib/electron/menus/menu-state.constant.ts
  packages/desktop/lib/electron/menus/menu.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/lib/helpers.ts
  packages/desktop/package.json
  packages/desktop/views/import-third-party-profiles/ImportThirdPartyProfilesRouterView.svelte
  packages/desktop/views/import-third-party-profiles/import-third-party-profiles-route.enum.ts
  packages/desktop/views/import-third-party-profiles/import-third-party-profiles.router.ts
  packages/desktop/views/import-third-party-profiles/index.ts
  packages/desktop/views/import-third-party-profiles/views/ImportProfilesView.svelte
  packages/desktop/views/import-third-party-profiles/views/SelectAppsView.svelte
  packages/desktop/views/import-third-party-profiles/views/index.ts
  packages/desktop/views/login/views/LoginView.svelte
  packages/desktop/views/onboarding/OnboardingRouterView.svelte
  packages/desktop/views/onboarding/onboarding-route.enum.ts
  packages/desktop/views/onboarding/onboarding-router.ts
  packages/desktop/webpack.config.ts
  packages/shared/src/components/interfaces/index.ts
  packages/shared/src/components/interfaces/option.interface.ts
  packages/shared/src/lib/auxiliary/third-party/actions/getThirdPartyPersistedProfiles.ts
  packages/shared/src/lib/auxiliary/third-party/actions/importThirdPartyProfiles.ts
  packages/shared/src/lib/auxiliary/third-party/actions/index.ts
  packages/shared/src/lib/auxiliary/third-party/actions/updateThirdPartyProfilesStore.ts
  packages/shared/src/lib/auxiliary/third-party/constants/database-key-separator.constant.ts
  packages/shared/src/lib/auxiliary/third-party/constants/index.ts
  packages/shared/src/lib/auxiliary/third-party/constants/network-name-to-stardust-network-id-map.constant.ts
  packages/shared/src/lib/auxiliary/third-party/enums/index.ts
  packages/shared/src/lib/auxiliary/third-party/enums/third-party-app-name.enum.ts
  packages/shared/src/lib/auxiliary/third-party/index.ts
  packages/shared/src/lib/auxiliary/third-party/interfaces/index.ts
  packages/shared/src/lib/auxiliary/third-party/interfaces/third-party-persisted-profile.interfaces.ts
  packages/shared/src/lib/auxiliary/third-party/stores/index.ts
  packages/shared/src/lib/auxiliary/third-party/stores/third-party-profiles.store.ts
  packages/shared/src/lib/auxiliary/third-party/utils/buildPersistedProfileFromThirdPartyPersistedProfile.ts
  packages/shared/src/lib/auxiliary/third-party/utils/index.ts
  packages/shared/src/lib/core/app/interfaces/managers/pincode-manager.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/src/lib/core/network/utils/getNetworkIdFromOnboardingNetworkType.ts
  packages/shared/src/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/src/lib/core/router/interfaces/router-event.interface.ts
  packages/shared/src/lib/core/router/routers/app-router.ts
  packages/shared/src/locales/en.json
  yarn.lock
Labels: type:feature

#2216 enhancement: add feature flags to app imports
  packages/desktop/features/electron.features.ts
  packages/desktop/features/interfaces/electron-features.interface.ts
  packages/desktop/features/onboarding.features.ts
  packages/desktop/lib/electron/menus/menu.ts
  packages/desktop/views/onboarding/onboarding-router.ts
  packages/shared/src/lib/features/types/onboarding-features.type.ts
Labels: type:enhancement

#2217 fix: login router
  packages/shared/src/lib/core/router/routers/app-router.ts
Labels: type:fix
