Repository bloomwalletio/bloom, pull requests merged in 2024-01, with the labels that each got.

#1680 chore: Iota -> IOTA
  packages/shared/src/lib/core/network/constants/default-network-metadata.constant.ts
Labels: type:enhancement, type:ui

#1683 enhancement: check ledger app version
  packages/shared/src/lib/core/ledger/constants/index.ts
  packages/shared/src/lib/core/ledger/constants/minimum-supported-iota-ledger-app.constant.ts
  packages/shared/src/lib/core/ledger/utils/determineLedgerConnectionState.ts
  packages/shared/src/lib/core/utils/index.ts
  packages/shared/src/lib/core/utils/version.ts
Labels: type:enhancement

#1689 fix: check ERC721 media mimetype against whitelist instead of expected type
  packages/shared/src/lib/core/nfts/actions/downloadNextNftInQueue.ts
  packages/shared/src/lib/core/nfts/enums/download-warning-type.enum.ts
  packages/shared/src/locales/af.json
  packages/shared/src/locales/ar.json
  packages/shared/src/locales/bg.json
  packages/shared/src/locales/ca.json
  packages/shared/src/locales/cs.json
  packages/shared/src/locales/da.json
  packages/shared/src/locales/de.json
  packages/shared/src/locales/el.json
  packages/shared/src/locales/en.json
  packages/shared/src/locales/eo.json
  packages/shared/src/locales/es-ES.json
  packages/shared/src/locales/es-LA.json
  packages/shared/src/locales/et.json
  packages/shared/src/locales/fa.json
  packages/shared/src/locales/fi.json
  packages/shared/src/locales/fr.json
  packages/shared/src/locales/he.json
  packages/shared/src/locales/hi.json
  packages/shared/src/locales/hr.json
  packages/shared/src/locales/hu.json
  packages/shared/src/locales/id.json
  packages/shared/src/locales/it.json
  packages/shared/src/locales/ja.json
  packages/shared/src/locales/ko.json
  packages/shared/src/locales/ku.json
  packages/shared/src/locales/lv.json
  packages/shared/src/locales/mk.json
  packages/shared/src/locales/nl.json
  packages/shared/src/locales/no.json
  packages/shared/src/locales/pl.json
  packages/shared/src/locales/pt-BR.json
  packages/shared/src/locales/pt-PT.json
  packages/shared/src/locales/ro.json
  packages/shared/src/locales/ru.json
  packages/shared/src/locales/si.json
  packages/shared/src/locales/sk.json
  packages/shared/src/locales/sl.json
  packages/shared/src/locales/sq.json
  packages/shared/src/locales/sr.json
  packages/shared/src/locales/sv.json
  packages/shared/src/locales/tr.json
  packages/shared/src/locales/uk.json
  packages/shared/src/locales/ur.json
  packages/shared/src/locales/vi.json
  packages/shared/src/locales/zh-CN.json
  packages/shared/src/locales/zh-TW.json
Labels: type:fix

#1687 fix: remainder address strategy
  packages/shared/src/lib/contexts/onboarding/actions/claimShimmerRewards.ts
  packages/shared/src/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/src/lib/core/wallet/actions/mintNft.ts
  packages/shared/src/lib/core/wallet/actions/send/createStardustOutputFromSendFlowParameters.ts
  packages/shared/src/lib/core/wallet/actions/send/signAndSendStardustTransaction.ts
  packages/shared/src/lib/core/wallet/actions/sendOutput.ts
  packages/shared/src/lib/core/wallet/constants/default-transaction-options.constant.ts
  packages/shared/src/lib/core/wallet/constants/index.ts
  packages/shared/src/lib/core/wallet/utils/getTransactionOptions.ts
  packages/shared/src/lib/core/wallet/utils/index.ts
Labels: type:fix

#1688 fix: prevent remainder outputs creating activities on multi address accounts
  packages/shared/src/lib/core/activity/utils/generateActivitiesFromBasicOutputs.ts
  packages/shared/src/lib/core/activity/utils/getDirectionFromTransaction.ts
  packages/shared/src/lib/core/activity/utils/getNonRemainderBasicOutputsFromTransaction.ts
  packages/shared/src/lib/core/activity/utils/index.ts
  packages/shared/src/lib/core/activity/utils/isOutputSubjectFromActiveAccount.ts
  packages/shared/src/lib/core/activity/utils/outputs/preprocessTransaction.ts
Labels: type:fix

#1690 fix: update ipfs gateway url
  packages/shared/src/lib/core/nfts/utils/rewriteIpfsUri.ts
Labels: type:fix

#1670 feat: fiat on ramp
  .github/workflows/reusable_build.yml
  packages/desktop/components/AccountSwitcher.svelte
  packages/desktop/features/analytics.features.ts
  packages/desktop/features/buy-sell.features.ts
  packages/desktop/features/features.ts
  packages/desktop/features/interfaces/analytics-features.interface.ts
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/constants/windows.constant.ts
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/preloads/transak.preload.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/public/transak.html
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/dashboard/buy-sell/BuySell.svelte
  packages/desktop/views/dashboard/buy-sell/index.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/desktop/views/dashboard/buy-sell/views/index.ts
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/desktop/webpack.config.ts
  packages/shared/src/lib/core/app/interfaces/index.ts
  packages/shared/src/lib/core/app/interfaces/managers/index.ts
  packages/shared/src/lib/core/app/interfaces/managers/transak-manager.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/src/lib/core/app/interfaces/transak-window-data.interface.ts
  packages/shared/src/lib/core/router/enums/dashboard-route.enum.ts
  packages/shared/src/lib/features/interfaces/features.interface.ts
  packages/shared/src/locales/en.json
  packages/shared/test/mocks/platform.mock.ts
Labels: type:feature

#1715 fix: opening mac deeplink when app is quit
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/lib/electron/utils/deep-link.utils.ts
Labels: type:fix

#1719 fix: Transak height growing but not shrinking
  packages/desktop/lib/electron/managers/transak.manager.ts
Labels: os:linux, os:windows, type:fix

#1750 feat: emit changeAccount event via WalletConnect
  packages/desktop/views/dashboard/drawers/dapp-config/views/ConfirmConnectionDrawer.svelte
  packages/shared/src/lib/auxiliary/wallet-connect/actions/approveSession.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/index.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/updateAccountForConnectedDapps.ts
  packages/shared/src/lib/auxiliary/wallet-connect/actions/updateAccountForDappSession.ts
  packages/shared/src/lib/auxiliary/wallet-connect/constants/supported-events.constant.ts
  packages/shared/src/lib/auxiliary/wallet-connect/enums/index.ts
  packages/shared/src/lib/auxiliary/wallet-connect/enums/wallet-connect-events.enum.ts
  packages/shared/src/lib/auxiliary/wallet-connect/utils/index.ts
  packages/shared/src/lib/core/account/actions/setSelectedAccount.ts
Labels: type:feature

#1752 enhancement: persist wallet tab index across sessions
  packages/desktop/views/dashboard/wallet/tab-section/TabSection.svelte
  packages/shared/src/lib/contexts/wallet/enums/index.ts
  packages/shared/src/lib/contexts/wallet/enums/wallet-tab-index.enum.ts
  packages/shared/src/lib/contexts/wallet/index.ts
  packages/shared/src/lib/contexts/wallet/stores/index.ts
  packages/shared/src/lib/contexts/wallet/stores/selected-wallet-tab-index.store.ts
Labels: type:enhancement

#1748 refactor+fix: Transak window position and size calculation
  packages/desktop/lib/electron/apis/electron.api.ts
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/shared/src/lib/core/app/interfaces/managers/transak-manager.interface.ts
  packages/shared/src/lib/core/app/interfaces/platform.interface.ts
  packages/shared/test/mocks/platform.mock.ts
Labels: type:fix, type:refactor

#1756 feat: adds Transak info panel and improves responsive layout
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/src/locales/en.json
Labels: type:feature

#1769 feat: initial campaign routes
  packages/desktop/features/analytics.features.ts
  packages/desktop/features/campaigns.features.ts
  packages/desktop/features/features.ts
  packages/desktop/features/interfaces/analytics-features.interface.ts
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/dashboard/campaigns/CampaignsRouterView.svelte
  packages/desktop/views/dashboard/campaigns/campaigns-route.enum.ts
  packages/desktop/views/dashboard/campaigns/campaigns-router.ts
  packages/desktop/views/dashboard/campaigns/index.ts
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignsGalleryView.svelte
  packages/desktop/views/dashboard/campaigns/views/index.ts
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/shared/src/lib/core/router/enums/dashboard-route.enum.ts
  packages/shared/src/lib/features/interfaces/campaigns-features.interface.ts
  packages/shared/src/lib/features/interfaces/features.interface.ts
  packages/shared/src/lib/features/interfaces/index.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#1771 feat: initialise empty campaigns gallery
  packages/desktop/features/campaigns.features.ts
  packages/desktop/lib/routers/actions/initialiseRouters.ts
  packages/desktop/views/dashboard/campaigns/campaigns-router.ts
  packages/desktop/views/dashboard/campaigns/views/CampaignsGalleryView.svelte
  packages/shared/src/lib/core/app/constants/external-allowed-links.constant.ts
  packages/shared/src/lib/features/interfaces/campaigns-features.interface.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#1776 enhancement: add breadcrumbs for campaigns tab
  packages/desktop/views/dashboard/campaigns/campaigns-router.ts
  packages/desktop/views/dashboard/campaigns/components/CampaignsGalleryItem.svelte
  packages/desktop/views/dashboard/components/Breadcrumbs.svelte
Labels: type:enhancement

#1781 enhancement: show collectibles gallery menu at all times
  packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte
Labels: type:enhancement

#1782 fix: draggable region when drawer is open
  packages/desktop/components/drawers/Drawer.svelte
Labels: type:fix

#1790 feat: add transak app connection panel
  packages/desktop/views/dashboard/buy-sell/components/TransakAccountPanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakConnectionPanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/TransakInfoPanel.svelte
  packages/desktop/views/dashboard/buy-sell/components/index.ts
  packages/desktop/views/dashboard/buy-sell/views/BuySellMainView.svelte
  packages/shared/assets/logos/transak.png
  packages/shared/package.json
  yarn.lock
Labels: type:feature

#1800 add initial campaign details layout
  packages/desktop/views/dashboard/campaigns/components/UserPositionCard.svelte
  packages/desktop/views/dashboard/campaigns/components/index.ts
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/shared/tailwind.config.js
Labels: type:feature

#1804 ui: campaign icons
  packages/desktop/views/dashboard/campaigns/components/Leaderboard.svelte
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/shared/package.json
  yarn.lock
Labels: type:ui

#1808 enhancement: reset campaign router on tab click
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
Labels: type:enhancement

#1783 enhancement: show loaded nft image avatars first
  packages/desktop/views/dashboard/wallet/panes/account-summary/components/AccountNetworkSummary.svelte
Labels: type:enhancement

#1815 feat: fetch campaigns on load
  packages/desktop/views/dashboard/campaigns/components/CampaignsGalleryItem.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignsGalleryView.svelte
  packages/shared/src/lib/contexts/campaigns/interfaces/campaign.interface.ts
  packages/shared/src/lib/contexts/campaigns/stores/campaigns-per-chain.store.ts
  packages/shared/src/lib/contexts/campaigns/stores/index.ts
Labels: type:feature

#1816 enhancement: campaign cards
  packages/desktop/views/dashboard/campaigns/components/CampaignParticipantsPill.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignStatusPill.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignTimestampPill.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignsGalleryItem.svelte
  packages/desktop/views/dashboard/campaigns/components/index.ts
  packages/shared/src/lib/contexts/campaigns/enums/campaign-status.enum.ts
  packages/shared/src/lib/contexts/campaigns/enums/index.ts
  packages/shared/src/lib/contexts/campaigns/index.ts
  packages/shared/src/lib/contexts/campaigns/interfaces/campaign.interface.ts
  packages/shared/src/lib/contexts/campaigns/utils/calculateCampaignStatus.ts
  packages/shared/src/lib/contexts/campaigns/utils/index.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#1822 ui: update campaigns icon to trophy
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/shared/package.json
  yarn.lock
Labels: type:ui

#1754 feat: enable external payment providers for Transak
  packages/desktop/lib/electron/managers/transak.manager.ts
  packages/desktop/lib/electron/preloads/transak.preload.ts
Labels: type:feature

#1823 enhancement: add rewards pill to campaign card
  packages/desktop/views/dashboard/campaigns/components/CampaignRewardsPill.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignsGalleryItem.svelte
  packages/desktop/views/dashboard/campaigns/components/index.ts
  packages/shared/src/lib/contexts/campaigns/interfaces/campaign.interface.ts
  packages/shared/src/locales/en.json
Labels: type:enhancement

#1828 ehancement: improve time diff
  packages/shared/src/lib/core/utils/time.ts
Labels: type:enhancement

#1833 fix: prevent crash in fetch L2 balance for account
  packages/shared/src/lib/core/layer-2/actions/fetchL2BalanceForAccount.ts
  packages/shared/src/lib/core/nfts/actions/updateErc721NftOwnership.ts
Labels: type:fix

#1839 enhancement: show total tasks
  packages/desktop/views/dashboard/campaigns/components/UserPositionCard.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
  packages/shared/src/lib/core/tide/apis/tide.api.ts
Labels: type:enhancement

#1846 feat: adds Tide logo in CampaignsGalleryView
  packages/desktop/views/dashboard/campaigns/components/TideLogo.svelte
  packages/desktop/views/dashboard/campaigns/components/index.ts
  packages/desktop/views/dashboard/campaigns/views/CampaignsGalleryView.svelte
Labels: type:feature

#1845 enhancement: polish campaign leaderboard
  packages/desktop/views/dashboard/campaigns/components/Leaderboard.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
Labels: type:enhancement

#1841 enhancement: sort campaigns by end time
  packages/desktop/views/dashboard/campaigns/views/CampaignsGalleryView.svelte
  packages/shared/src/lib/contexts/campaigns/constants/campaign-end-date-cut-off.constant.ts
  packages/shared/src/lib/contexts/campaigns/constants/index.ts
  packages/shared/src/lib/contexts/campaigns/interfaces/campaign.interface.ts
  packages/shared/src/lib/contexts/campaigns/utils/calculateCampaignStatus.ts
  packages/shared/src/lib/core/tide/enums/index.ts
  packages/shared/src/lib/core/tide/enums/tide-listing-status.enum.ts
Labels: type:enhancement

#1848 fix: improve leaderboard layout
  packages/desktop/views/dashboard/campaigns/CampaignsRouterView.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignHeader.svelte
  packages/desktop/views/dashboard/campaigns/components/CampaignNft.svelte
  packages/desktop/views/dashboard/campaigns/components/Leaderboard.svelte
  packages/desktop/views/dashboard/campaigns/components/UserPositionCard.svelte
  packages/desktop/views/dashboard/campaigns/views/CampaignDetailsView.svelte
Labels: type:fix

#1849 chore: update bloom ui 19.10
  packages/shared/package.json
  yarn.lock
Labels: type:chore, type:ui
