Repository bloomwalletio/bloom, pull requests merged in 2024-04, with the labels that each got.

#2215 enhancment: fix and polish sidebar toasts
  packages/desktop/views/dashboard/components/DashboardSidebar.svelte
  packages/desktop/views/dashboard/components/toasts/BackupToast.svelte
  packages/desktop/views/dashboard/components/toasts/VersionToast.svelte
  packages/shared/src/lib/contexts/onboarding/actions/backupInitialStronghold.ts
  packages/shared/src/lib/contexts/settings/actions/exportStronghold.ts
  packages/shared/src/lib/core/stronghold/utils/getDefaultStrongholdName.ts
  packages/shared/src/locales/de.json
  packages/shared/src/locales/en.json
  packages/shared/src/locales/es-ES.json
  packages/shared/src/locales/fr.json
  packages/shared/src/locales/hi.json
  packages/shared/src/locales/nl.json
  packages/shared/src/locales/pt-BR.json
  packages/shared/src/locales/sv.json
  packages/shared/src/locales/zh-CN.json
Labels: type:enhancement

#2244 fix: crash from not removing handler
  packages/desktop/lib/electron/managers/third-party-profiles.manager.ts
Labels: type:fix

#2241 chore: enable third party imports
  packages/desktop/features/electron.features.ts
  packages/desktop/features/onboarding.features.ts
  packages/desktop/views/import-third-party-profiles/views/SelectAppsView.svelte
  packages/shared/src/locales/en.json
Labels: type:chore

#2247 release: desktop 1.0.0
  packages/desktop/lib/electron/menus/menu.ts
  packages/desktop/package.json
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityAssetSection.svelte
  packages/shared/package.json
  packages/shared/src/lib/core/app/constants/privacy-policy-version.constant.ts
  packages/shared/src/locales/de.json
  packages/shared/src/locales/en.json
  packages/shared/src/locales/nl.json
  packages/shared/src/locales/pl.json
  yarn.lock
Labels: type:chore

#2261 fix: crash on advanced settings if no feature toggles exist
  packages/desktop/views/settings/views/advanced/ToggleFeatures.svelte
Labels: type:fix

#2264 feat: add profile diagnostics popup
  packages/desktop/components/popup/Popup.svelte
  packages/desktop/components/popup/popups/ProfileDiagnosticsPopup.svelte
  packages/desktop/features/login.features.ts
  packages/desktop/lib/auxiliary/popup/enums/popup-id.enum.ts
  packages/desktop/views/login/components/ProfileCard.svelte
  packages/desktop/views/login/components/ProfileCardActionsMenu.svelte
  packages/desktop/views/login/components/index.ts
  packages/shared/src/lib/auxiliary/third-party/utils/buildPersistedProfileFromThirdPartyPersistedProfile.ts
  packages/shared/src/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/src/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/src/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/src/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-10-to-11.ts
  packages/shared/src/lib/core/profile/migrations/alpha/alpha-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/beta/beta-profile-migration-0-to-1.ts
  packages/shared/src/lib/core/profile/migrations/beta/beta-profile-migration-map.ts
  packages/shared/src/lib/core/profile/migrations/prod/prod-profile-migration-5-to-6.ts
  packages/shared/src/lib/features/interfaces/login-features.interface.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2260 fix: slow login times while loading activities
  packages/shared/src/lib/core/profile/actions/active-profile/login.ts
Labels: type:fix

#2278 chore: increment desktop version to `1.0.1`
  packages/desktop/package.json
  packages/shared/package.json
Labels: type:chore

#2285 enhancement: adds Transak loading timeout fallback
  packages/desktop/lib/electron/preloads/transak.preload.ts
Labels: type:enhancement

#2248 fix: adds camera permissions in macOS
  packages/desktop/electron-builder-config.ts
  packages/desktop/entitlements.mac.plist
  packages/desktop/lib/electron/managers/transak.manager.ts
Labels: os:macos, type:fix

#2318 feat: initial scam nft detection
  packages/desktop/views/dashboard/collectibles/components/CollectibleDetails.svelte
  packages/desktop/views/dashboard/wallet/panes/account-summary/components/AccountNetworkSummary.svelte
  packages/shared/src/lib/core/activity/utils/isVisibleActivity.ts
  packages/shared/src/lib/core/nfts/actions/buildNftFromNftOutput.ts
  packages/shared/src/lib/core/nfts/enums/download-warning-type.enum.ts
  packages/shared/src/lib/core/nfts/interfaces/nft.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/persisted-nft.interface.ts
  packages/shared/src/lib/core/nfts/utils/checkIfNftShouldBeDownloaded.ts
  packages/shared/src/lib/core/nfts/utils/index.ts
  packages/shared/src/lib/core/nfts/utils/isScamIrc27Nft.ts
  packages/shared/src/lib/core/nfts/utils/isVisibleNft.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2331 feat: add blocklist for NFT scam detection
  packages/desktop/App.svelte
  packages/shared/src/lib/core/nfts/utils/isScamIrc27Nft.ts
  packages/shared/src/lib/core/utils/constants/nft-blocklist-json-url.constant.ts
  packages/shared/src/lib/core/utils/interfaces/nft-blocklist.interface.ts
  packages/shared/src/lib/core/utils/json/nft-blocklist.json
  packages/shared/src/lib/core/utils/stores/nft-blocklist.store.ts
Labels: type:feature

#2333 chore: removes Link component
  packages/shared/src/components/Link.svelte
  packages/shared/src/components/index.ts
Labels: type:chore

#2340 fix: change GHA node version from 20.x to 20.10.0
  .github/workflows/ci.lint.yml
  .github/workflows/ci.test.yml
  .github/workflows/ci.ts.yml
  .github/workflows/reusable_build.yml
Labels: type:fix

#2341 enhancement: NftGalleryItem
  packages/desktop/components/menus/CollectibleDetailsMenu.svelte
  packages/desktop/components/popup/popups/StardustActivityDetailsPopup.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectibleDetails.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/AssetPillsForActivity.svelte
  packages/desktop/views/dashboard/wallet/tab-section/activity/components/row-sections/ActivityAssetSection.svelte
  packages/desktop/views/dashboard/wallet/tab-section/portfolio/components/TokenListRow.svelte
  packages/shared/package.json
  packages/shared/src/components/activities/stardust/info/StardustGenericInformation.svelte
  packages/shared/src/components/molecules/NftGalleryItem.svelte
  packages/shared/src/components/nfts/AssetPillsForNft.svelte
  packages/shared/src/components/nfts/AsyncPillsForNft.svelte
  packages/shared/src/components/nfts/index.ts
  packages/shared/src/components/pills/AsyncStatusPill.svelte
  packages/shared/src/components/pills/ExpiredPill.svelte
  packages/shared/src/components/pills/NetworkTypePill.svelte
  packages/shared/src/components/pills/NftStandardPill.svelte
  packages/shared/src/components/pills/TimelockActivityPill.svelte
  packages/shared/src/components/pills/TimelockPill.svelte
  packages/shared/src/components/pills/UnclaimedActivityPill.svelte
  packages/shared/src/components/pills/UnclaimedPill.svelte
  packages/shared/src/components/pills/index.ts
  packages/shared/src/lib/core/activity/utils/outputs/getExpirationDateFromOutput.ts
  packages/shared/src/lib/core/nfts/actions/buildNftFromNftOutput.ts
  packages/shared/src/lib/core/nfts/interfaces/nft.interface.ts
  packages/shared/src/lib/core/nfts/utils/getSpendableStatusFromUnspentNftOutput.ts
  packages/shared/src/lib/core/wallet/actions/burnNft.ts
  packages/shared/src/lib/core/wallet/actions/claimActivity.ts
  yarn.lock
Labels: type:enhancement

#2364 fix: balance breakdown alignment
  packages/desktop/components/popup/popups/BalanceBreakdownPopup.svelte
  packages/shared/src/components/atoms/BalanceSummaryRow.svelte
  packages/shared/src/components/atoms/BalanceSummarySection.svelte
Labels: type:ui

#2371 feat: adds CollectionGalleryView
  packages/desktop/features/collectibles.features.ts
  packages/desktop/views/dashboard/collectibles/Collectibles.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectiblesTabs.svelte
  packages/desktop/views/dashboard/collectibles/components/index.ts
  packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectionsGalleryView.svelte
  packages/desktop/views/dashboard/collectibles/views/index.ts
  packages/shared/src/lib/core/nfts/constants/collectibles-tabs.constant.ts
  packages/shared/src/lib/core/nfts/constants/index.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/selected-collectibles-tabs.store.ts
  packages/shared/src/lib/features/interfaces/collectibles-features.interface.ts
  packages/shared/src/locales/en.json
Labels: type:feature

#2383 refactor: move json file functions to json file manager
  packages/desktop/lib/electron/managers/json-file.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
Labels: type:refactor

#2384 refactor: move code from main to electron settings manager
  packages/desktop/lib/electron/interfaces/electron-settings.interface.ts
  packages/desktop/lib/electron/interfaces/index.ts
  packages/desktop/lib/electron/interfaces/window-state.interface.ts
  packages/desktop/lib/electron/managers/electron-settings.manager.ts
  packages/desktop/lib/electron/processes/main.process.ts
Labels: type:refactor

#2373 enhancement: add deny list nft download permission
  packages/desktop/views/settings/views/collectibles/DownloadNftPermissions.svelte
  packages/shared/src/lib/core/nfts/utils/checkIfNftShouldBeDownloaded.ts
Labels: type:enhancement

#2391 feat: adds collection data in CollectionsGalleryView
  packages/desktop/views/dashboard/collectibles/views/CollectionsGalleryView.svelte
  packages/shared/src/lib/core/nfts/interfaces/collection.interface.ts
  packages/shared/src/lib/core/nfts/interfaces/index.ts
  packages/shared/src/lib/core/nfts/interfaces/nft.interface.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/selected-account-collections.store.ts
  packages/shared/src/lib/core/nfts/types/collections.type.ts
  packages/shared/src/lib/core/nfts/types/index.ts
  packages/shared/src/lib/core/nfts/utils/getCollectionFromNft.ts
  packages/shared/src/lib/core/nfts/utils/index.ts
  packages/shared/src/lib/core/nfts/utils/isVisibleCollection.ts
Labels: context:collectibles, type:feature

#2395 feat: creates CollectionsGallery and CollectionsGalleryItem
  packages/desktop/views/dashboard/collectibles/components/CollectionsGallery.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionsGalleryItem.svelte
  packages/desktop/views/dashboard/collectibles/components/index.ts
  packages/desktop/views/dashboard/collectibles/views/CollectionsGalleryView.svelte
  packages/shared/src/components/molecules/NftGalleryItem.svelte
  packages/shared/src/locales/en.json
Labels: type:feature

#2396 feat: adds CollectionDetails
  packages/desktop/views/dashboard/collectibles/components/CollectionDetails.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionsGallery.svelte
  packages/desktop/views/dashboard/collectibles/components/CollectionsGalleryItem.svelte
  packages/desktop/views/dashboard/collectibles/components/index.ts
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/desktop/views/dashboard/components/Breadcrumbs.svelte
  packages/shared/src/components/molecules/NftGalleryItem.svelte
  packages/shared/src/lib/core/nfts/interfaces/collection.interface.ts
  packages/shared/src/lib/core/nfts/stores/index.ts
  packages/shared/src/lib/core/nfts/stores/selected-collection.store.ts
  packages/shared/src/lib/core/router/routers/collectibles-router.ts
Labels: type:feature
